README.md
System/mounted-disk-capacity.5s.sh

Show mounted disk capacity: free space and total size

Mounted Disk Capacity Plugin

---

README.md

added self to contributors

---

Lifestyle/current_task.1m.rb
README.md

Sometimes it's easy to get distracted during daily work. This plugin is supposed
to remind you about the task you are supposed to right now.
It stores the task in a `task` file in the script's directory. It also takes care about creating the file if it does not exist (however it doesn't care if you got write access ;) )
You can change the task, by calling the script with one argument like this:
`./current_task.1m.rb "Finish important business"`

Current task reminder script 

---

Dev/Docker/docker-status.1m.sh
README.md

Add docker status plugin

---

Dev/HackerNews/hacker_news.rb

Displays a few of the top stories from hacker news in a nice dropdown. Provides a link, the number of comments, and an indicator of the score of the story, color-coded.

added plugin for getting new stories from hacker news.

---

Dev/Xcode/xcode-version.1h.sh
README.md

added xcode-version plugin

---

Weather/ForecastIO/weather.15m.py

Made forecast.io weather plugin a bit more snazzy: auto location lookup and more data.

Updated forecast.io plugin; more data, more fun

---

Dev/HackerNews/hacker_news.rb
README.md

Added basic error handling to the plugin. Also added it to the list of plugins in the Readme and put my name in the contributors list.

Updated HackerNews Plugin and Readme

---

README.md

hour_logger is a Python app for managing hours and the money you make at work that is compatible with BitBar.

Added link to hour_logger in Readme

---

Weather/Wunderground.30m.rb

* Fixes how the top-level constants are handled to ensure reasonable defaults
* Suppress unnecessary stack traces and show a nice (human readable) error message in the menu instead

Minor bug fixes for Weather Underground plugin

---

Network/website-status
Network/website-status.sh

Get the status of your website. Get the status "ok", "redirected" and "error". Also the http_code is available.

new plugin website-status

---

README.md

[readme] minor style update

---

Web/EasyDigitalDownloads/edd.15m.py

When an error, show exception details in dropdown instead of BitBar menu

EasyDigitalDownloads: Add better exception handling

---

Music/cmus.10s.sh

Shows current track similar to Spotify, iTunes and Vox plugin but for cmus.
https://github.com/cmus/cmus
Screenshot:

Add cmus music player

---

Finance/currency-tracker.py
README.md

Hi ! 
I wrote a Python script allowing to fetch some currencies values.
I created it because I'm going soon to Canada and I wanted to see the current values of the money to make the best deal while exchanging.
You can track multiple currencies at once, and choose the one you use to comparate. No API key needed, based on fixer.io.
Hope you guys can enjoy it !

Add currency tracker

---

Bitcoin/winkdex.com/winkdex.1m.sh
README.md

Added a new plugin to show the Bitcoin price based on the WinkDex.com index.

Adding WinkDex.com plugin

---

Dev/Semaphoreci/project-list.5m.js
README.md

add Semaphoreci project list plugin

---

Network/dnsswitcher.1d.sh
README.md

Hi
I just wrote DNS switcher plugin
some sites are banned by my internet network provider 
I can't access them through Google DNS
so I often change my network DNS on Network Preferences
I have tried this blog post http://osxdaily.com/2013/07/01/change-network-location-quickly-mac-os-x/ for alternative, but it will disconnect and reconnect the connection, it's bad for me

add DNS switcher plugin

---

Lifestyle/todo.30s.sh
README.md

Show list of todo items and a count using a very simple global todo list in ~/.todo.

Add simple todo list viewer and count

---

Dev/Travis/travis-check.2m.py

Refactor to remove the travis dependency, so that this script can
be run without installing any extra dependencies.
Also, as part of the refactor, remove the need for passing the
Github token, instead using Travis' own tokens.
In addition, add a few extra features:
- repos_to_check is not required - if it is not supplied the script
will go and fetch all repos under your account.
- add INCLUDE_PULL_REQUESTS which will fetch build data about the
latest pull requests. Off by default, so only commits are counted
- add SECRET_FILTER_BY_STAR which is a hidden feature of the Travis
api that lets you star repositories, and subsequently filter them.
In essence behaving like `repos_to_check` but without maintaining
the list inside of this script.
It'd be great to get @tomkinsc's approval before …

Dev/Travis/travis-check: refactor & remove travis

---

Dev/Homebrew/brew-updates.1h.sh

Click on the upgrade count upgrades everything.
Click on a single package upgrades only the package.

Added click action to upgrade homebrew packages

---

README.md
Web/HackerNews/hacker_news.rb

Clicking on the Comments line now sends the user to the comments page.

Make the Hacker News comments clickable

---

Finance/currency-tracker.1m.py

Just added the meta informations on the currency tracker script

Implement Bitbar plugin metadata on currency-tracker

---

Time/fuzzyclock.1s.py

It was crashing between 11:37:30 and 12:00:00
because it was looking for num_word[13]
Also removed redundant tests, and simplify rounding to nearest five.

Fix fuzzy clock issues close to noon and midnight

---

Network/ssh.sh
README.md

I added this under Network section, but not entirely sure if that's the right place to put that in.

Add SSH plugin

---

Weather/ForecastIO/weather.15m.py
Weather/OpenWeatherMap/weather.15m.py

Updated plugin metadata

---

Tutorial/is_darkmode.sh

As I mentioned in the bitbar repo, I think plugins should be able to easily tell if Dark Mode is enabled to adjust text color and other factors. 
Bitbar pull request: https://github.com/matryer/bitbar/pull/155
This pull request is for a quick tutorial to show you can change the text color depending if Dark Mode is enabled.

Tutorial for using Darkmode Environment Variable

---

README.md

https://github.com/matryer/bitbar/pull/54

added contributor name

---

README.md
System/trash-collector.5s.sh

Trash Collector is a plugin for BitBar that enables you to empty your trash.
- Empty trash
- Count trash
- Open trash

Trash Collector Plugin

---

Dev/Semaphoreci/project-list.5m.js

this is needed so it can work on white osx theme also

remove color=white from semaphoreci plugin

---

README.md
Web/Twitch/play-with-livestreamer.5m.js

Because twitch.tv use flash it's better to use [livestreamer](http://docs.livestreamer.io/) to watch streams. This plugin lists top 10 streams by game and when clicked open in vlc using livestreamer

Add Twitch livestreamer plugin

---

Dev/Nagios/nagios.sh

Host down is still a work in progress and further refinement to be worked on.

Nagios status plugin

---

System/Battery/keyboard-system_profiler.1m.sh

keyboard battery percentage, 2nd method

---

Network/internal-ip.1h.sh

Get the first IP address, based on network adapter sorting  at network system preference panel

Getting the first active adapter

---

Dev/Logs/tail.5s.sh

added simple tail plugin

---

Weather/ForecastIO/weather.15m.py

Fix for merged syntax error, added href link to forecast.io.

Weather plugin updates

---

System/Battery/keyboard-system_profiler.1m.sh

Previous version (perl script) doesn't works fine. This really works (explained and tested here #84 )

really works

---

Time/worldclock.1s.sh

* Fixes typographical errors in metadata end tags
* Adjusts the desc field for clarity, and removes the unnecessary dependencies field

Minor world clock plugin fixes

---

Weather/ForecastIO/weather.15m.py

Fixed cardinal calculation to be more in sync with forecast.io. Added next hour weather data and rearranged some line items.

More weather updates

---

Weather/Wunderground.30m.rb

Corrects mistakes in the metadata end tags

Fix typos in metadata for Weather Underground plugin

---

Weather/Wunderground.30m.rb

Adjust metadata text

---

Dev/GitHub/github_watch.1h.rb

Watch GitHub project stars :star:

Add GitHub Watch

---

Dev/Vagrant/vagrant.30s.pl

terminal required?, color and bash without separation with pipes?

works with v1.4

---

Dev/RabbitMQ/rabbitmq-status.1m.php

Here is a plugin I created to check the status of my RabbitMQ server.
PHP is not part of your Tested Language section, but work fine nonetheless with the appropriate Shebang.

add plugin RabbitMQ Status

---

README.md
Time/timezone.5s.sh
Weather/OpenWeatherMap/weather.15m.py

- New Timezone Plugin
- openweathermap language feature
- In the openweathermap add on I now use the description as the "main" won't get translated.

Timezone, openweathermap language, Readme

---

WorldEvents/quake.1m.sh

Added a plugin for getting all significant earthquakes in the last 30
days

QuakePlugIn Added

---

Weather/Wunderground.30m.rb

Minor fix to adjust unit used for pressure in SI output.

Correct the unit used for pressure in SI output

---

Web/ProductHunt/producthunt-tech-hunts.1d.py

This plugin lists today's featured Product Hunt tech posts.

Product Hunt - Featured Hunts

---

System/ejector.5s.sh

Add image and about url meta data for Ejector Plugin

---

System/trash-collector.5s.sh

Add image and about url meta data for Trash Collector Plugin

---

Time/alarmclock.1s.sh

Alarm Clock is a plugin for BitBar that notifies/make a sound at a specific time.

Alarm Clock Plugin

---

Time/countdown.1s.py

Add Countdown plugin

---

Travel/travel-time.5m.php

Travel time plugin minor update (improved display on error, comments, typos, ...)
- update metadata description
- fix delay and googleMapsLink generation on Exception
- add Refresh menu item on error.
- update airport command path and add comments
- add comments and fix typos

Travel time plugin minor update

---

Dev/Docker/docker-status.1m.sh

- Added some emojis to display
- Added exited containers also to the list.

Updated docker plugin 

---

System/clipboard-history.3s.sh

Include $USER env var in tmp_dir path to allow for a history folder per
user.

Add support for multiple users

---

Network/vpn-check.3s.sh

Save that precious menu bar space :grin:

Update to VPN Check output

---

Network/website-status.sh

add the #!/bin/bash for website-status.sh

---

Dev/Redis/checkRedisMemory.sh

Screenshot: http://i.imgur.com/ikCSVBq.png

Added redis memory usage plugin. Connects via SSH

---

Weather/OpenWeatherMap/weather.15m.py

Gracefully handle inability to connect to openweathermap.org

---

System/uptime.1m.sh

I personally consider better to not have text changing so much in the bar.

Changed uptime to show only the uptime on the title

---

Dev/Bamboo/bamboo_build_status.1m.sh

I've written and am using this plugin which displays the build status for a Bamboo build.  I thought others might find it useful.

Add Bamboo build status plugin v1

---

Bitcoin/huobi.com/huobiprice.1s.py
Dev/GitHub/notifications.30s.py
Dev/Travis/travis-check.2m.py
Finance/currency-tracker.1m.py
Finance/gfinance.5m.py
Finance/hours.1m.sh
System/memusage.5s.py
System/usbInfo.10s.py
Time/countdown.1s.py
Time/fuzzyclock.1s.py
Travel/renaultze.10m.py
Weather/ForecastIO/weather.15m.py
Weather/OpenWeatherMap/weather.15m.py
Web/EasyDigitalDownloads/edd.15m.py
Web/ProductHunt/producthunt-tech-hunts.1d.py

I updated the shebangs for primarily python files to use the more portable #!/usr/bin/env & the corresponding python version.

updated shebangs

---

Network/external-ip.1h.sh

Hi. Found this awesome little gem so thinking to contribute a bit. :)

Add a copy to clipboard action for external ip.

---

Bitcoin/huobi.com/huobiprice.1s.py
Dev/GitHub/notifications.30s.py
Dev/Travis/travis-check.2m.py
Finance/currency-tracker.1m.py
Finance/gfinance.5m.py
Finance/hours.1m.sh
System/memusage.5s.py
System/usbInfo.10s.py
Time/countdown.1s.py
Time/fuzzyclock.1s.py
Travel/renaultze.10m.py
Weather/ForecastIO/weather.15m.py
Weather/OpenWeatherMap/weather.15m.py
Web/EasyDigitalDownloads/edd.15m.py
Web/ProductHunt/producthunt-tech-hunts.1d.py

Reverts matryer/bitbar-plugins#172
The previous change did not take into account the different environment of BitBar.
See [this comment](https://github.com/matryer/bitbar-plugins/pull/172#issuecomment-174638832).

Revert shebang update

---

Time/weeknumber.1m.sh

Added a plugin in directory 'Time' to display the week number.

Add plugin to display week number

---

Time/pomodoro.sh

https://en.wikipedia.org/wiki/Pomodoro_Technique

Added Pomodoro Timer 🍅

---

Lifestyle/githubzen.1m.py

Add GitHub Zen plugin

---

Weather/OpenWeatherMap/weather.15m.py

Replaced weather API key- uses same as other plugin

---

System/ejector.5s.sh

- Simplify Diskutil Information parsing
- Support for Eject only All Disk Images or Physical Volumes
Proposal from issue https://github.com/matryer/bitbar-plugins/issues/188

Ejector v1.1

---

Dev/Vagrant/vagrant.30s.pl
System/Battery/keyboard-system_profiler.1m.rb
System/Battery/mouse.1m.sh

typos to bitbar.image close tag

---

Bitcoin/bitcoin.de/last.30s.sh

Plugin to show bitcoin price from german bitcoin exchange bitcoin.de

plugin for bitcoin price from bitcoin.de

---

Ethereum/ethusd.1m.sh

This plugin shows the last price for Ethereum in USD.

Ethereum price plugin

---

Dev/GoSquared/gosquared-now.30s.py

Added plugin to show GoSquared visitors online now count

---

Dev/Jenkins/jenkins-multiple-projects-status.1m.sh

for Multiple Jenkins Projects plugin

Adding schema configuration

---

Dev/Sentry/sentry.5m.js

https://getsentry.com
A crash reporting service.

Plugin for Sentry

---

Bitcoin/bitfinex.com/bitfinex_btcusd.sh

Getting BTCUSD from Bitfinex public rest api, more info at: http://docs.bitfinex.com/#rest

Added Bitfinex BTCUSD Price

---

Music/lastfm.10s.rb

Ruby script for grabbing now playing/last played information from a Last fm account

last.fm now playing

---

Dev/Jenkins/jenkins-multiple-projects-status.1m.sh

- Removes usage of password in favour of token
- Fixes issue with tailing the end of the file as JSON keys are unsorted

Use token and fix issue with tailing json

---

Dev/CircleCI/circleci-check.5m.py

Each row has a link to the corresponding webpage (github repository or CircleCI build).
Thanks to Chris Tomkins-Tinch for the inspiration!

Add CircleCI plugin

---

Weather/OpenWeatherMap/weather.15m.py

Added utf-8 encoding support for weather description.

Fix for #206

---

System/screenshot.1d.py

This adds the ability to create screenshots that can be saved, uploaded or copied to clipboard

Added Screenshot Util

---

Weather/ForecastIO/weather.15m.py

As requested at https://developer.forecast.io to address #242

Added link back to forecast.io

---

System/mas.1d.sh

added mac app store

---

Finance/transferwise-currency-tracker.1m.py

More accurate and reliable than the existing api.fixer.io forex plugin

Added Transferwise currency tracker

---

Lifestyle/random_quotes.5m.sh

This script grabs a list of quotes and shows a random one to the user on each refresh.

Script to show random quotes created

---

Weather/ForecastIO/weather.15m.py

* Solution for #198 
* Better support for international location
* Better error handling/messaging
* Support for URL opening in bitbar v1.4+

Weather v2.0.0

---

Dev/Jenkins/jenkins-all-jobs.status.1m.py

This plugin reports the status of all jobs on a Jenkins instance.
Thanks!!

Add Jenkins All Jobs Plugin

---

Dev/VisualStudioOnline/vso-pull-requests.1m.js

I've created a plugin which lists Pull Requests in Visual Studio Online

Added VSO Pull Requests plugin

---

Dev/Vagrant/vagrant.2m.pl

Another Vagrant script for Bitbar

Another Vagrant script for Bitbar

---

Lifestyle/sleepingtime.1m.sh

Added a variable `start_cycle` and `end_cycle` to change the range of cycles to show in the menu bar.
The example image has 
start_cycle=1
end_cycle=7

Rewrote the sleepingtime plugin, easier to customize

---

Dev/Gitlab/gitlab_projects.js

Sorry I realised the last snippet i used to display times ago had bug...

missing space in gitlab plugin

---

Dev/Monitoring/process-monitoring.1s.sh

This plugins enables the monitoring of a single process metrics from top.

Adding process monitoring plugin

---

Dev/Java/java_version.12h.py

This plugin displays the current version of Java installed on your
system. If it is the newest version it will be displayed in green
on the task bar. If there are newer versions, your current Java
version will be displayed in orange and the context menu will have
a list of newer versions which you can click on.
Clicking on a newer version takes you to a download page which will
let you download and install the latest Java version.

add java_version plugin

---

System/clipboard-history.3s.sh

- Added `refresh=true` parameters to buttons that change the state of the plugin, to reflect the changes immediately. 
- Also, added variable `CLIPBOARD` to store the value of `pbpaste` instead of calling the command every time.

Added `refresh` parameters to buttons

---

Time/ts-convert.sh

I added a script to convert unix timestamps to a date.
Open Features:
- detect and switch between seconds and miliseconds

Timestamp to date

---

Email/gmail-checker.sh

Add exec permission and screenshot

---

Music/songkick.1d.py

This plugin will show upcoming music events in the neighborhood by using [Songkick](songkick.com) API. 
In addition, This plugin needs Songkick API KEY which will provide from [here](https://www.songkick.com/developer).

Added a plugin to show newly music events on Songkick.

---

.test.py
.travis.yml

The script tests files for the following:
- File is readable
- File is executable
- Correct shebang
- Correct metadata
- Metadata image is an actual image
- Code passes respective languages lint
During PRs the tests will only check touched files.
On master branch builds, it checks all files.

Add travis testing of scripts

---

Tools/BitBar/bitbar-plugin-installer.1d.php

Plugin for installing BitBar plugins.

add bitbar-plugins-installer plugin

---

Dev/CircleCI/circleci-check.5m.py

Add running builds (+ use real CircleCi colors)

---

BitBar/version.12h.rb

Adding new version plugin for BitBar which checks current installed version against latest from GitHub

Adding new bitbar version check plugin

---

Dev/Jira/jira.1m.sh

added bitbar plugin for jira that displays all blockers, assigned tasks and open storys.

added jira plugin

---

Finance/Ethereum/ethusd.1m.sh

There were some changes to the API.

Fix for the Ethereum price plugin

---

.travis.yml

I think gem document is no need in CI.

Bit improve CI performance

---

Bitcoin/bitfinex.com/bitfinex_all.sh

Another plugin to show all info from Bitfinex Ticker REST API.

Added all info from Bitfinex REST API Ticker

---

Lifestyle/todoist.1m.py

You have to add api_key in this file as follow.
```
api_key = 'xxxxxxxxxxxxxxxxx'
```

Added plugin to check today's task on todoist

---

Network/netinfo.60s.sh

This plugin will gather various network information on your network interfaces and internet connection status. In addition it allows for a speedtest (via speedtest-cli) to be run.

Added netinfo plugin

---

Lifestyle/todo.15m.rb

- for code clarity, linting, etc.

Todo Colour -- Tweaks

---

Dev/Docker/docker-status.1m.sh

I'm using Dlite (https://github.com/nlf/dlite) instead of docker-machine and i just added support to this feature

Support dlite

---

Web/HackerNews/hacker_news.rb

Fix implicit conversion of Nil to String exception
Corrected use of parameters
Added begin/rescue block around output generation to prevent one story to break the rest of the script

Fix conversion exception and parameter definition of hacker news script

---

Time/itstimeto.15m.py

I write a BitBar plugin that shows notification emoji for this time.

added itstimeto

---

Weather/OpenWeatherMap/weather.15m.py

Using 'env' to select python version in case users have modified their system or moved it to a new location.

use env to select python

---

Dev/Redmine/redmine-show-my-task.1m.rb

Hi! :cat2: 
I created plugin for redmine.
It can shows my open ticket :sushi:
I'd like to register it as a bitbar official plugin!

Add plugin for redmine.

---

Dev/Emacs/emacs-package-updates.1d.sh

Add error hander for me :blush:

[Emacs Package Updates] Add error handler

---

Dev/BitbucketServer/stash-pull-requests.2m.rb

Reverts matryer/bitbar-plugins#360

Revert "Revert "Adds Bitbucket Server (Stash) Pull Request plugin""

---

Sports/live_cricket.2m.py
Sports/live_tennis.1m.py

The plugin was not able to find the winner of a set if the set was decided in a tiebreaker. 
Also changed shebang.

bugfix at generating match info in tennis plugin

---

Lifestyle/taskwarrior.4m.py

this plugin brings the commandline taskwarrior utility to the menu bar

initial submission of taskwarrior plugin

---

Weather/ForecastIO/weather.15m.py

- The SI unit for distance (should be velocity) was wrongly km/h, it should be m/s
- The plugin crashed if there were no internet connection, added check to see if internet is available.

Corrected SI-units and added internet on check

---

Weather/ForecastIO/weather.15m.py

Replaced with correct service URL.

Replaced unsolicited URL with forecast.io

---

Bitcoin/cryptonator.com/btc-price-gbp.py
Bitcoin/cryptonator.com/btc-price-usd.py
Blackcoin/blk-price-gbp.py
Blackcoin/blk-price-usd.py
Dogecoin/doge-price-gbp.py
Dogecoin/doge-price-usd.py
Litecoin/ltc-price-gbp.py
Litecoin/ltc-price-usd.py

Fixed all the silly things and added a few more plugins for good measure.

Crypto tickers simplified

---

BitBar/version.12h.rb

prevents showing and error diretly when re-connecting to wifi

Adding internet check to bitbar version plugin

---

Tools/PagerDuty/pagerduty.30s.rb

A couple of new features
- Use localtime for incident time.
- Use "option" key to see longer incident descriptions
- Click the description to get to the client url.

Localtime, description and client url

---

Web/Feedly/feedly.rb

The existing "feedly.rb" gets a feed on Feedly. I wanted to check tech blog more effectively 🍻 
Example:

Add a script to get a news feed on Feedly

---

System/killdock.1d.sh

Kill Dock. It useful when Dock is missing on main display
* Script is executable now

Added KillDock plugin

---

System/infinit-drive.10s.py

A [bitbar]() plugin for [infinit drive](infinit.sh)
https://github.com/strages/infinit-drive-journal-stats-bitbar-plugin

infinite drive plugin

---

System/Battery/battery-dot.1h.swift

shows battery status for trackpad, keyboard and laptop. Based on the trackpad-dot plugin by @milch

Extended battery level indicator plugin

---

Dev/GitHub/github-trending.1h.rb

This plugin is github daily trending viewer.
Please see also https://github.com/mfks17/bitbar-plugin-github-trending.
Thanks!! :smile:

Add  bitbar plugin for github daily trending viewer.

---

Web/HackerNews/hacker_news.1m.rb

I just made some fixes to the plugin post issue #415 , plus I am sending a minor improvement of adding sublinks for news comments.
@keithamus @caneroj1 @thameera @oliviernt

#415 - HackerNews plugin, fix file error and sublinks.

---

System/mas.1d.sh

I think this is what I intended originally.

Add check for `mas` install and update count

---

Dev/GitHub/repo-issues.5m.js

A script that retrieves pull requests and issues, greying pull requests that have been addressed by an issue. See https://github.com/tomgenoni/bitbar-ghissues for more details.

Adding repo issues script.

---

Finance/Ethereum/ethbtc.sh

Add Ethereum/BTC price plugin

---

Web/Cornify/cornify.1m.sh

This plugin allows you to see random unicorns in the menu bar!

introduce cornify plugin

---

Music/itunes.10s.sh

added some try/catch to deal with error when iTunes is started but no track is selected.
also:
replaced play/pause symbols with emojis and added immediate refresh when pause/next/prev is pressed

error handling

---

Dev/Emacs/emacs-package-updates.1d.sh

Sometimes melpa.org returns nil. This Pull Request rescues it.

[Emacs Package Updates] Rescue melpa.org returns nil

---

Web/EasyDigitalDownloads/edd.15m.py

It's helpful to know what average sales are for the month compared to the month before, as well as the ASP ("Average Sales Price")

Add monthly daily sales avg & avg selling price

---

Lifestyle/jawbone.10m.py

As the title says, this plugin will retrieve today's steps and sleep duration from the Jawbone UP API. You need to retrieve an access token as described here: https://jawbone.com/up/developer/authentication

New Plugin: Get today's steps and sleep duration from the Jawbone UP API

---

Finance/ginmon.1d.sh

Simple performance tracker for [ginmon.de](https://www.ginmon.de).

Add Ginmon performance tracker

---

Web/Twitch/livestreamer-now-playing.5m.js

Removes streams that aren't actually live.

Filter streams that are playlisting

---

Time/waketime.1m.sh

Added my glorious plugin.
It shows the time since your mac last woke up.

Added waketime

---

Time/waketime.1m.sh

Waketime v1.0.1

---

Dev/Homebrew/package_manager.7h.py

Following #466, here is an update exposing latest Python packages updates.

Expose Python package updates via Pip

---

Dev/Homebrew/package_manager.7h.py

FAO: @kdeldycke
* Add support for pip3, node, atom, ruby gems
* Fixup brew cask checking
* Don't die on errors

Bunch of updates for package_manager

---

Dev/Homebrew/package_manager.7h.py

Changelog:
* Add changelog.
* Add reference to package manager's issues.
* Force Cask update before evaluating available packages.
* Update screenshot.
CC: @tresni @keithamus

Update Package Manager to v1.3

---

Dev/Homebrew/package_manager.7h.py

FAO: @kdeldycke
A couple tweaks after investigating what @keithamus brought up with linked packages.

Fix a couple issues with npm/apm parsing

---

Web/Reddit/redditnotify.30s.py

This plugin gets mail from your Reddit inbox and lets you know when you get mail. When you do get mail, you also get a preview of the message. The plugin needs to be configured before use, but the plugin will prompt you to configure it if it isn't.
Requires **Python** and the **P**ython **R**eddit **A**PI **W**rapper (**PRAW**).
[Click to Download](http://illumineighti.tk/#bitbar://openPlugin?src=https://raw.githubusercontent.com/Shugabuga/bitbar-plugins/master/Web/Reddit/redditnotify.30s.py)

"Reddit Notifications" - A plugin to display your Reddit notifications.

---

Dev/Codeship/codeship-single.30s.py
Dev/Codeship/codeship.1m.py

Added a couple of plugins for Codeship, one for all projects and the other for a single project.

Added Codeship plugin

---

System/virtualbox-vms.5s.sh

Add ACPI shutdown option

---

Dev/Shell/aka.1h.sh

Fixes issue I had where better (more efficient) syntax lead to all lines not printing.  Don't understand it.

Plugin akalias

---

Music/spotify.10s.sh

Pretty simple change. When you move forward/back a track the name of the artist and song only updates when the script runs. This will refresh it upon moving tracks, updating that information immediately.

Updates the artist/song text immediately when you move tracks

---

Weather/ForecastIO/weather.15m.py

add daily summary to ForecastIO/weather

---

Dev/Homebrew/package_manager.7h.py

Changelog:
* Work around the lacks of full pip upgrade command.
* Fix UnicodeDecodeError on parsing CLI output (closes #493).

Update Package Manager plugin to v1.6

---

Music/spotify.10s.sh

New try with a PR for making the Spotify plugin handle spaces in the script path.

Make spotify plugin handle spaces in script path.

---

Music/nowplaying.5s.sh

Another PR, this time for the nowplaying plugin to handle spaces in the script path.

Handle spaces in the script path.

---

Music/spotify.10s.sh

PR for adding icons/emojis for play, pause, next and previous to the Spotify plugin.

Add menu icons.

---

Finance/moex.1m.rb

A new plugin for BitBar. The Russian Ruble exchange rates from Moscow Exchange.
USD - United States dollar 🇺🇸
EUR - Euro 🇪🇺
CHF - Swiss franc 🇨🇭
JPY - Japanese yen 🇯🇵
CNY - Chinese yuan 🇨🇳
CAD - Canadian dollar 🇨🇦
TRY - Turkish lira 🇹🇷
[https://github.com/RomanKrasavtsev/moex-bitbar-plugin](https://github.com/RomanKrasavtsev/moex-bitbar-plugin)

Add new plugin moex.1m.rb

---

System/showhide-files.1d.py

add plugin showhide-files.1d.py

---

Dev/Gitlab/gitlab_projects.js

* Fixes shebang line
* Fixes HTTPS

Fixes shebang line in GitLab projects plugin

---

Dev/Travis/travis-check.2m.py

Travis CI plugin enhancements.

Updated TravisCI Plugin to v1.2, fix for #492

---

System/currentFiles.1h.rb

I added my plugin to the repository.

Added currentFiles.1h.rb plugin for editing files

---

Dev/Homebrew/homebrewcask.1d.sh

- delete "From:"
- Add symbol for 'no casks'

little fix

---

System/load_temp_fan.10s.sh

Just adding this bar, I thought would be helpful for those who likes minimalism and only useful mission critical metrics.  Cheers.
Ivan.

New plug-in.  Load Average/Temperature/Fan Speed Bar

---

Lifestyle/todo-md.30s.pl

Hi,
I have created a new BitBar plugin. Please add it the repository plugin.
It's similar to [Simple Todo Tracker](https://getbitbar.com/plugins/Lifestyle/todo.30s.sh). Of cause I can request to the author to modify it, but I think it should be keep simply. So I created new one.
Kenji
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matryer/bitbar-plugins/586)

New plugin: simple todo tracker for markdown

---

Environment/solaredge.5m.py

Auto convert watt/lbs units, catch fetching errors
W -> kW -> MW -> GW
lbs -> tons

Update SolarEdge plugin to 1.1

---

System/mysql-status.1m.sh

Hi,
I have created a new BitBar plugin. Please add it the repository plugin.
It shows the mysql server status installed on localhost. And show the shortcuts for managing server instance. 
Kenji

New plugin: mysql server status

---

System/mysql-status.1m.sh

Hi,
I have just updated mysql status plugin. It is related to a pull request of a new plugin similar to this.
https://github.com/matryer/bitbar-plugins/pull/598
Kenji
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matryer/bitbar-plugins/599)

Update plugin: mysql server status

---

Dev/MetaPackageManager/meta_package_manager.7h.py

Latest stable release of the v1.11.0 BitBar plugin fixes parsing of versions and upgrade of packages from Homebrew Cask v1.1.0.

Upgrade to Meta Package Manager v1.11.0

---

AWS/ecs-cluster.10m.sh

Displays count, memory and CPU stats for your Amazon ECS cluster.

initial version of the  Amazon ECS Cluster plugin

---

Weather/ForecastIO/weather.15m.py

Update to support a more precise location lookup using CoreLocationCLI
Requires [CoreLocationCLI](https://github.com/fulldecent/corelocationcli/releases) to use native lookup, will automatically fallback to IP lookup if the bin is not found.

Updated Weather Plugin

---

System/Battery/battery-status.20s.py

Show current Battery change percent and time remaining (dropdown)

Add Battery percentage and time remaining plugin

---

Dev/MetaPackageManager/meta_package_manager.7h.py

This version brings some tiny rendering tweaks.
Changelog:
* Do not render emoji in BitBar plugin menu entries.
* Do not trim error messages rendered in BitBar plugin.
* Do not strip CLI output. Keep original format.

Upgrade Meta Package Manager plugin to v2.1.1.

---

Travel/travel-time.5m.php

Hello,
I changed my handle and would be happy to reply to any issues with my plugin.
updating bitbar.author.github metadata
Thank you,
Yann.

Update metadata for Travel Time plugin

---

Dev/RabbitMQ/rabbitmq-status.1m.php

Hello,
I changed my handle and would be happy to reply to any issues with my plugin.
updating bitbar.author.github metadata
Thank you,
Yann.

Update handle metadata for RabbitMQ Status

---

System/host-switcher.1d.sh

Simple plugin to switch between multiple hosts files

Host file switcher

---

Dev/RescueTime/rescuetime.1h.py

Date was hardcoded so here is fixed version

fix rescue time plugin date handling

---

Dev/Gitlab/gitlab_status.10m.sh

add gitlab status

---

Environment/conda-envs.15m.py

https://github.com/nok/conda-envs :octocat: 
Happy coding,
Darius

Add 'conda-envs' plugin

---

Email/gmail-checker-improved.1m.pl

I personally like the numerical counter that is on the OTHER gmail plugin. However, that is SH and has no features.

Modified gmail-checker-improved to include a numerical counter on bar

---

Dev/MetaPackageManager/meta_package_manager.7h.py

In sync with the new `mpm` 2.3.0 release, this is the brand new BitBar plugin.
Changelog:
* Make it easier to change the font, size and color of text in BitBar plugin.
* Move error icon in BitBar plugin to the front of manager name.

Upgrade to Meta Package Manager plugin v2.3.0.

---

Environment/conda-envs.15m.py

Changes:
- Add used memory usage for each env
- Add comments to improve code quality
https://github.com/nok/conda-envs#output
Happy coding,
Darius

Update plugin: conda-envs

---

Lifestyle/todo-md.30s.pl

Hi,
I have just updated todo list management plugin.
It is enabled to hide comment line and to categorize by label.
Kenji
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matryer/bitbar-plugins/663)

Update plugin: LifeStyle/todo-md.30s.pl

---

System/launch-agents.10s.sh

This plugin, influenced by the `brew-services` plugin, views and manages user Launch Agents (in `~/Library/LaunchAgents/`).

new plugin: Launch Agents

---

Time/shiftstats.30s.py
Web/Instagram/igs.10m.py

New Plugin:Instagram stats

---

Time/shiftstats.30s.py

Small fixes and text improvements

Shiftstats

---

Lifestyle/taskpaper.10s.py

Taskpaper Today 1.1

---

System/launch-agents.10s.sh

- Menu items now make more sense, e.g. "View Error Log"
- Service PID is displayed
- Service error code is displayed
- Screenshot is updated to reflect new menu options

Launch Agents plugin 1.1: Improved UI/UX

---

Twitter/twitter.1m.py

File permissions are now correct. Bugs fixed.

Added Twitter plugin

---

System/quickfolders.10m.sh

Plugin to show folder structure and quick access to folders. For more info see https://blog.aruehe.io/quickfolders-a-bitbar-plugin/

quickfolders plugin

---

Sports/bundesliga.1h.py

Shows the next matchday of the Bundesliga using the API of http://www.openligadb.de

Next Matchday of the Bundesliga

---

Music/mpd-control.20s.sh

show mpd's current song title and toggle play/pause when click the title

add mpd title and control

---

Dev/Vagrant/vagrant.30s.pl

I will propose revising the plugin which I also use conveniently.
The plugin was originally developed by @alexandregz .
The revise is enable to copy the path to the vagrant directory to the clipboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matryer/bitbar-plugins/697)

Update plugin: Dev/Vagrant/vagrant.30s.pl

---

Lifestyle/write-into-menubar-bitbar-plugin.1s.sh

You need to install Alfred Powerpacks and my Alfred Workflow to use
this plugin. Details on my repo: https://github.com/yigitkonur/write-into-menubar

Bitnami Alfred Workflow (to write text into Menubar by Alfred Commands)

---

Web/Twitch/livestreamer-now-playing.5m.js

Favourites support 
Cut down on noise if you have lots of followers by manually writing in
your favourite streamers. Only these will be counted in the tray, and
in the future only these will have notifications / etc sent about them.

livestreamer-now-playing: Favourites support

---

Network/checkhosts.1m.go

I still can not get this to work in the interpreted version.
See https://github.com/matryer/bitbar/issues/394 for more details

Add checkhosts

---

Lifestyle/time_on_earth.10m.rb

This adds a plugin to display how long you are already living on this planet:
This was created to not only have a plugin for the remaining time. Sometimes it's good to think positive 😉

Add a plugin to display your time on earth

---

Dev/MetaPackageManager/meta_package_manager.7h.py

In sync with the new `mpm` 2.5.0 release, this is the brand new BitBar plugin.
Changelog:
* Support displaying of multiple non-blocking errors.
* Minor update of documentation format and layout.

Upgrade to Meta Package Manager plugin v2.5.0.

---

Weather/metar.5m.rb

For pilots that want to see the current conditions for their home airport.

Add the metar aviation weather plugin

---

Tools/octoprint.1m.sh

3dprinter control with octoprint webapi

New plugin : octoprint client (3dprinter control)

---

Lifestyle/moon-phase.1h.js

A plugin that shows the current moon phase.

New plugin showing current moon phase as emoji

---

Tools/octoprint.1m.sh

Update plugin: Tools/octoprint.1m.sh

---

Web/Instagram/igs.10m.py

Fixed bio encoding issue

---

Dev/Git/daily-standup.sh

A plugin to show git commits from last 24 hours.  And more.
More info, screenshots here - [daily-standup](https://github.com/krishkumar/daily-standup)

New plugin: Git Commits for Daily Standup

---

Travel/gwr-wifi-status.1m.py

First time doing a Pull Request so if I've done something wrong then sorry in advance.
Just wanted to contribute a plugin I've created to check Wifi Status on Great Western Railway (GWR) trains.
You can find the project here with a screenshot - [https://github.com/Adam2Marsh/bit-bar-GWR-Wifi-Status-Plugin](https://github.com/Adam2Marsh/bit-bar-GWR-Wifi-Status-Plugin)

Added new Plugin for GWR Wifi Status

---

System/DarkModeToggle.sh

Small typo, nothing of real significance.

Changes type for Desactivate

---

Bitcoin/bitx.co/buy-and-sell.1m.py

Buy and sell prices for XBT/ZAR from [BitX](https://bitx.co) Bitcoin exchange.
Preview:

New plugin: BitX buy and sell prices (XBT/ZAR)

---

Lifestyle/habitica.1h.js

closes https://github.com/matryer/bitbar-plugins/issues/742

refactor(habitica): use of default property fixes undefined

---

Lifestyle/todoist.1m.py

This PR enhances some functions.
- support multibyte (issue #750 )
- support across year due tasks
- support todoist APIv7

function enhancement

---

Finance/cryptocurrency-rates-uk.10m.py

Hello! This is a crypto currency price checker for the UK market. Price is based in pound sterling.

Added Cryptocurrency rates UK plugin

---

Lifestyle/todoNotePlan.15m.rb
System/currentFiles.1h.rb

Hi,
I finally finished and tested the NotePlan plugin for Bitbar. Could you merge it in? Thanks.
Richard

TodoNotePlan Plugin

---

Dev/GitHub/pull-requests.5m.js

Otherwise this fails pretty much every time I wake up my mac as wifi hasn't connected yet

Silently catch errors when checking PRs

---

Dev/Dropper/dropper.1m.js
Dev/Hosting/DigitalOcean/digitalocean.1h.js

Dropper shows status of DigitalOcean droplets in your menu bar.
1. List droplets
2. Open droplet page in browser
3. Open droplet in console
4. View other information like IP address, size, memory, etc. readily.

Add Dropper plugin

---

Cryptocurrency/Ripple/xrpusd.1m.sh

Converted Nikita Zhavoronkov's (@Har01d) Ethereum plugin to XRP.

New Plugin: Cryptocurrency: Ripple XRPUSD

---

Cryptocurrency/Bitcoin/bitoex.com/bitoex-buy-and-sell.10s.sh

[BitoEX](bitoex.com) is a popular bitcoin exchange in Taiwan.
Plugin show the buy and sell values basically.

Add bitoex to Cryptocurrency/Bitcoin/

---

Dev/Hosting/DigitalOcean/digitalocean.1h.js

Multiple token support for multiple accounts or teams

Added multiple token support

---

Cryptocurrency/btcmarkets.10s.sh

Added BTC Markets ticker

---

Dev/Hosting/DigitalOcean/digitalocean.1h.js
E-Commerce/Shopibar.15m.js

pr-new-plugin-shopibar

---

Music/spotify.10s.sh

Add Lyrics search for current song on Music/spotify

---

Cryptocurrency/Bitcoin/btc.5m.sh
Cryptocurrency/Ethereum/eth.5m.sh
Cryptocurrency/Litecoin/ltc.5m.sh

Three scripts, pulled from the works of many others. figured I'd give them back.

adding my crypto trackers

---

Cryptocurrency/coin-alert.5s.sh

Coin Alert is a plugin for BitBar that notifies and make a sound when less than or greater than cryptocurrency price from CoinMarketCap.

Add Coin Alert

---

Web/Twitch/livestreamer-now-playing.5m.js

Changes:
- Move from livestreamer to streamlink (a livestreamer fork) as livestreamer appears to be dead.
- Add native notifications support.
- Chit chat support
- A bunch of refactoring.

livestreamer-now-playing 2.2

---

System/trash-collector.5s.sh

Fix empty trash

---

Cryptocurrency/CoinbasePrices.sh

Displays Bitcoin, Ethereum and Litecoin prices from Coinbase

Display Coinbase Prices

---

Cryptocurrency/Bitcoin/coinbase.com/balance.1h.sh

Signed-off-by: Bryan Stone <aegixx@gmail.com>

Coinbase Balance - Move to v2 API (v1 is deprecated)

---

Time/age-ticker.1s.py

this plugin shows your age in years with decimals. the number is always increasing

add age ticker plugin

---

Finance/gfinance.5m.py

This makes sure the stock symbols always appear in alphabetical order.
It also simplifies the code a bit by using join instead of a for loop.

Sort stocks and simplify code a bit

---

Cryptocurrency/Bitcoin/coinbase.com/balance.1h.sh

Signed-off-by: Bryan Stone <aegixx@gmail.com>

Coinbase Balance Enhancement: Add account balances and deltas

---

Finance/yahoo-stock.1m.py

The format now looks like `TCKR $1,845.37 +2.92 (+0.16%)`

Improve stock price formatting

---

Network/vpn-country-flag.js

Let me know how I can improve it so it gets merged. Thanks!

Added vpn country flag plugin

---

Cryptocurrency/99-crypto.py

original coinmarketcap(down) api is in comments in case someone wants it

switch to cryptomate

---

Dev/Drone/drone-status.1m.sh

Add a bash script to check the status of the most recent build for Drone CI.

Add drone-status

---

Dev/TOTPOpenAuth/totp.20s.sh

Added TOTP OAuth Token Generator plugin using [OATH Toolkit](http://www.nongnu.org/oath-toolkit/). OATH Toolkit can be installed using `brew install oath-toolkit`

Added TOTP OAuth Token Generator plugin

---

Cryptocurrency/Bitcoin/tr-markets.1m.py

btcturk new api fix.

---

Dev/Gogs/gogs-issues.5m.js

Display the amount of issues from a self hosted Gogs instance.

Add gogs issue checker

---

Network/ping.10s.sh

fix #769: ping works when when sub 1ms

---

Dev/CloudflareDevelopmentMode/cloudflare.1m.js

Plugin created to quickly manage the development mode of a Cloudflare account to avoid having to login to their web interface all day long as changes are made on your various Cloudflare-based sites.

Added Cloudflare Development Mode

---

Dev/CloudflareDevelopmentMode/cloudflare.1m.js

Needed to instruct users to change API key and email.  Also added a better image for plugin site.

Cloudflare Instructions

---

Weather/emojiWeather.30m.js

Publishing a new plugin for BitBar.

Add emojiWeather

---

System/DoNotDisturb.1s.py

Add a new plugin in System: DoNotDisturb, which allows you to turn on
the "Do Not Disturb" only for certain time.

Add a new plugin in System: DoNotDisturb

---

.travis.yml

- Use the latest compatible version with ruby 2.0 rubocop gem

Fix travisci

---

Time/date-picker.1m.sh

Adds a new plugin: date-picker

date-picker added

---

Email/mu-email-checker.sh

Count total number of emails in inbox, unread mail and drafts indexed with [mu].(http://www.djcbsoftware.nl/code/mu/)
Also includes the output for unread emails in the drop down menu.

Email checker for mail indexed with mu

---

Time/countdown_timer_2.1s.py

Improved countdown_timer with UI to set task/time, and better parsing/rendering of time.

Add a new plugin countdown_timer_2

---

Sports/cricket_bar.1m.php

Hi,
Here's a new one: "Displays live cricket score of a selected match, using data from ESPNcricinfo or Cricbuzz."
And if you're wondering why there's another cricket scores plugin, from the info page:
"Inspired by, and much respect to, Anup Sam Abraham and his Live Cricket Scores plugin.
Anup’s plugin lets you see scores from several matches at once, whereas Cricket Bar focusses on one match at a time, as well as giving you the option to get scores from Cricbuzz in addition to ESPNcricinfo."
Hope it's OK.
Regards,
Adi

Cricket Bar plugin

---

Sports/cricket_bar.1m.php

- option to set timezone
- selected match ID reset on feed change
- timeout set on Curl connect

cricket_bar updates (v1.1)

---

Lifestyle/org-agenda.30m.rb

Discription can be found here https://github.com/yqrashawn/bitbar-plugin-agenda

add org-agenda, check emacs agenda view in bitbar

---

Tools/JsonUtils.1d.sh

This plugin can validate, format, compact JSON entity.

Add a new plugin 'JsonUtils'

---

Dev/Trello/trello.30s.py

this adds a basic trello bar, to list cards in different status
it uses the following environment variables:
- TRELLO_KEY to retrieve from https://trello.com/app-key
- TRELLO_TOKEN to retrieve from https://trello.com/app-key
- TRELLO_BOARD
- TRELLO_BOARDNAME (if not defining TRELLO_BOARD) 
- TRELLO_STATES which defaults to  'Next,In Progress'
- TRELLO_USER
this looks like this

Added new plugin Trello

---

Cryptocurrency/bitso-btc-eth-xrp.30s.sh

Plugin that displays Bitso buy prices of Bitcoin, Ethereum, Ripple in MXN

Add bitso plugin

---

Cryptocurrency/Dogecoin/doge-usd.py

(The old API url endpoint wasn't loading anymore)

Updated API endpoint and variable names.

---

Time/cal.1d.sh

Shows a calendar of the current, previous and next year:

Add cal plugin

---

Sports/live_tennis.1m.py

fixed an issue when empty score value is passed in api response

Fixes #959

---

Cryptocurrency/garlicoin.1m.sh

Created a cryptocurrency plugin to check your Garlicoin balance.

Added new crypto-plugin for garlicoin

---

Web/EasyDigitalDownloads/edd.15m.py

v2 allows us to remove an API request, which is nice.
Also, I added User Agent headers to make the request play more nicely with some server security settings.

Update for Easy Digital Downloads v2 API

---

Dev/Docker/docker-sync-status.1m.sh

Docker-Sync is a ruby gem used for helping Docker achieve faster sync times with mounted volumes on macOS.
This plugin modifies a file that Docker-Sync is watching and checks for a change in the Docker-Sync log to determine if the sync is still active.
http://docker-sync.io/
https://imgur.com/a/vpCUK

Docker-Sync Status

---

Time/ProcessBarOfYear.1d.sh

Dividing the year into 100 pieces.
https://github.com/cnfn/BitBarPlugins/tree/master/ProcessBarOfYear

Add plugin: Process Bar of Year

---

Weather/yahoo_temp.5m.py

- Created a weather plugin using Yahoo weather API
- Displays the current condition (cloudy, snowy, etc...) and temperature of the user's chosen city
- Requires users to 1) follow the description in the source code for getting Endpoint URL from Yahoo's website 2) set temperature between Fahrenheit and Celsius

Created a weather plugin

---

Lifestyle/muezzin.5m.sh

Here is my plugin: https://github.com/mehmetakiftutuncu/Muezzin-BitBar

Add Muezzin plugin

---

Weather/yahoo_temp.5m.py

- Changed from using subprocess to urllib
- Changed from users manually going to Yahoo website for new weather URL for their location to automatically knowing through IP or just changing 'city' and 'region' parts in the code

Yahoo weather plugin version 2

---

Dev/GitHub/notifications.30s.py

[GitHub Notifications] Replace any pipes in title

---

Web/isItUp.5s.js

Added [Is It Up Plugin](https://github.com/ZacharyDavidSaunders/IsItUp-BitBarPlugin)

Added "Is-It-Up" Plugin v1.1

---

Dev/Gitlab/gitlab_ci.1m.py

Shows currently running pipelines from your GitLab in your bar.

Add GitLab CI plugin

---

Weather/Wunderground.30m.rb

Good for no internet connection or other errors

Add Default Error Handling to Wunderground Plugin

---

Dev/Hosting/DigitalOcean/digitalocean.1h.js

close https://github.com/matryer/bitbar-plugins/issues/1020

fix DigitalOcean droplet created_at getMonth() problem

---

Dev/Shell/run-fastlane.rb

Run [fastlane](https://github.com/fastlane/fastlane) directly from menu bar!

Adding fastlane plugin

---

Time/cal.1d.sh

FAO: (@busterc)
Display for "today" is broken a little bit at least in my environment.  Mainly this PR improves it.  Could you review and comment about my patch?
Anyway, thanks for your simple and good plugin 📆

cal.1d.sh: Style view

---

System/trash-collector.5s.sh

Fix Issue https://github.com/matryer/bitbar-plugins/issues/1024

Use trash size instead of count

---

Time/CalendarLite.1m.sh

Add a new plugin which shows a clock. A simple calendar pops up when it is clicked. The current date **is marked with a parenthesis.** 
Last month and next month are also present in deeper level.

Add a new plugin named Calendarlite: a clock with a simple calendar, in which current date is marked

---

Lifestyle/todoist.1m.py

This make it possible to support both python2 & 3.
Requested with #835

support python3

---

System/DoNotDisturb.1s.py

Update the missing image of DoNotDisturb

Update an image in DoNotDisturb

---

Music/spotctl.10s.sh

I'm using https://github.com/Spotifyd/spotifyd (because I don't like to run a freaking electron to play my music) and this plugin helps me control it from bitbar.
Make sure you have https://github.com/jingweno/spotctl installed and configured.

Add Spotify control plugin using spotctl

---

Sports/worldcup.1m.php

Just a simple script for the current competition. Uses the API provided by http://worldcup.sfg.io.
Done in PHP, because that's what I know.

Displays current & daily scores from the World Cup

---

Sports/worldcup.1m.php

Made a few changes based on feedback.
Added Emoji Flags to all countries
Added goalscorers to games where available
Match names in dropdown are links to FIFA's official site.

Added emoji flags and goalscorers

---

Network/viscosity-active-connection.1s.sh

This PR adds the plugin that shows the name of the first active `Viscosity` connection.

Add Viscosity active connection plugin

---

Network/emoji-active-network-interface.sh

Authored in accordance with the provided guidelines.

Add Emoji Active Network Interface Indicator to the Network plugins.

---

Dev/GitHub/github-review-requests.5m.py

This PR adds `Github review requests` plugin.
It shows a list of PRs that need to be reviewed.

Add Github review requests plugin

---

Cryptocurrency/Ethereum/eth_wallet_balances.1m.py

I'm so late to the party. Wish I'd known about bitbar sooner :)
My first plugin :tm: 
It does this: https://schluting.com/temp/bitbar-eth-bal.png
...for configured wallets. All balances shown in $USD.

Add ETH wallet and token balances plugin.

---

Dev/MacMux/mac-mux.sh

A simple utility to manage tmux sessions from the menu bar.

Plugin: tmux utility for Mac

---

Time/progress.1h.sh

New Plugin: Progress Bar of Year, Month and Day.

---

Messenger/slack-unread.1s.py

Thanks for the script! Please see my updates made below to enhance the script.
* Added error checking to be more user friendly
* Added support for Private channels and DMs
* Optimized code

Added Multiple enhancements to Slack unread count script

---

Tools/PagerDuty/pagerduty.30s.rb

Passing API v2 paramenter correctly

Fixed matryer/bitbar-plugins#1062

---

Web/commitstrip.1h.sh

Read comics on http://www.commitstrip.com

Plugin: CommitStrip

---

Cryptocurrency/Cardano/cardano.10s.py

You can monitor Cardano (ADA)'s latest price via CoinRanking.com API.

Cardano (ADA) Price Monitor

---

Tools/sensibo.60s.sh

I've created a plugin that shows my current Sensibo pods, allowing me to also have some basic control over them.
The plugin looks like this:
For suggestions and/or issues -- the repo containing this plugin is can is [@niladam/sensibo-bitbar](https://github.com/niladam/sensibo-bitbar).

[NEW PLUGIN] Sensibo Plugin

---

Network/wireguard.sh

Adds a script that allows the user to connect/disconnect a Wireguard VPN tunnel and see the status of the connection.

Add Wireguard script

---

Dev/GitHub/github-review-requests.5m.py

This PR adds dark mode support

github-review-requests - dark mode support

---

Finance/currency-tracker.1h.py

The [Fixer](https://fixer.io) currency conversion API has changed and now requires an API key to access. Fixer does offer a free plan but it is limited to 10,000 API calls per month and will require users of this plugin to first register an account.
The `currency-tracker.1h.py` plugin currently fails to run:
```python
Traceback (most recent call last):
File "/Users/konrad/Code/personal/bitbar-plugins/Enabled/currency-tracker.1h.py", line 26, in <module>
result = urllib2.urlopen(url).read()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File …
```

Update currency-tracker plugin API

---

Web/Instagram/igs.10m.py

All user data is now under the `"graphql"` dictionary;
Some keys changed names;
Also, images structure is drastically different.

Fixed data structure for instagram data retrieval;

---

Tools/addnote.5s.py

Add Notes to Apple Notes App

---

Lifestyle/votd.1d.rb

Added plugin for verse of the day
[Readme](https://github.com/harryloewen/bitbar-votd)

New Plugin: Verse of the Day

---

Network/sent-received.1s.sh

Displays total sent and received wifi data for current sesssion.

New plugin: "sent/received"

---

Lifestyle/habitica.1h.js

Attempt to support dailies as best I can

Minor updates, work for dailies

---

Finance/currency-tracker.1h.py

Previous endpoint was returning 404, this is the new endpoint of the api.

Update exchangeratesapi endpoint

---

Web/xkcd.1h.sh

On my system I need to disable line wrapping by using the `-w 0` to make it work properly

[UPDATE] base64 Image Decoding

---

Dev/sshMenu/SshMenu.sh

SSH Menu plugin added

---

Tools/screen.2m.sh

Add GNU screen plugin

---

.travis.yml
Music/music-controls-info.10s.sh
Music/music-controls-like.10s.sh
Music/music-controls-next.10s.sh
Music/music-controls-playpause.10s.sh
Music/music-controls-previous.10s.sh

Plugins to play/pause, trigger next track, trigger previous track and favorite a song. Work with cmus, iTunes, Spotify, and pianobar (some buttons only work with select music players, i.e. pianobar has no previous track option)

Added music control button plugins

---

Network/wakeonlan.sh

I created a new plugin called wakeonlan. This, as the name suggests, sends 'magic packets' to the target computer on the same local area network to turn it on.

New Plugin: wakeonlan

---

Music/spotify.10s.sh

+ fix the Lyrics button not working
+ do some cleanup of the code
+ add `CLEAN_ALBUM_NAMES` option (on by default)

Update Spotify plugin

---

Web/Beeminder/beeminder.10m.py

This PR adds a new plugin that pulls your [Beeminder](https://www.beeminder.com) goals

New plugin: Beeminder goals

---

Dev/Emacs/emacs-package-updates.1d.sh

Hi there,
This is a plug-in I made. I've added Refresh item for convenience.
Thanks.

Add Refresh item to emacs-package-updates.1d.sh

---

Finance/robinhood.1m.py

Just need to install https://github.com/Jamonek/Robinhood with `pip install robinhood`

Robinhood.1m.py Portfolio Plugin

---

Lifestyle/nightscout.1m.sh

This is a plugin specifically for Diabetics who use a Continuous Glucose Monitor and who track their data using Nightscout (http://www.nightscout.info/). It just does a simple REST call and formats the data for BitBar

Nightscout plugin

---

System/top5-memory-consuming-applications.sh
System/top5-memory-consuming-processes.sh

top 5 memory-consuming applications

---

Music/spotctl.10s.sh

Fix spotctl shorten function

---

Network/ip-flag.2m.rb

with the flag, I thought having the IP address and ISP provider name would be helpful.
adding a new plugin just for these additional feature is an overkill. hence proposing change to what is available.
Hope @MatzFan is ok with this.

Adding additional details as multi-line menu

---

Web/WaniKani/waniKaniStats.5m.rb

Added a new WaniKani stats plugin to display user Account, Lesson, and Review details for the WaniKani Japanese learning platform.

New WaniKani Stats plugin

---

Web/WaniKani/waniKaniStats.5m.rb

* Fixed an issue causing incorrect progress to display
when starting a new level
* Fixed an issue where the incorrect total items would display
in the progress section

Fixed two issues with the WaniKani plugin

---

.test.py
Messenger/bitbar-slack-team-notifications/README.md
Messenger/bitbar-slack-team-notifications/package.json

I previously removed `package.json` as it was causing the tests to fail. Trying to add this back so its easier for people to run this

Add missing files

---

Weather/weather-rmw.10m.py

This riff combines some ideas from the emoji weather plugin in this folder, with the weather info source and structure of the weather.15m.py script by @seripap . I find it compact, nice looking, and useful.

Adding my riff on the weather.15m.py script.

---

Lifestyle/memento_mori.py

User needs to provide a birthday date to the script.
Script assumes everyone lives up to age 77.
When the script runs, user will see " - $x days left -" on their status bar

Add Memento Mori plugin

---

Tools/desktop_cleaner.rb

Add [Desktop cleaner](https://github.com/tomorrowkey/desktop_cleaner)
A tool for moving outdated files on Desktop to backup directory.

Add desktop_cleaner

---

Web/PocketBar/pocket.10m.py

* cache added
* keyring started to be used
* no more third party tools are needed to authorize the app
* more optimal API calls

Pocket Bar: new large release

---

System/totp.30s.sh

-this uses yubikey manager cli https://github.com/Yubico/yubikey-manager to generate codes
-clicking on a menubar item copies that code to your clipboard

add yubikey totp codes

---

Time/switchtimezones.5s.sh

This plugin allows switch between several timezones. Zones and their names can be set in the $TZS array. Click on any timezone in the menu will switch timezone shown in the bar.
Click on Epoch, YMD, or ISO 8601 will copy current time to the clipboard.

Add Switch Timezones plugin

---

System/fan-speed.5s.sh

The fan speed plugin didn't work for me. I managed to fix it with same changes .
Please confirm that it works for you too.

Fixed fan speed plugin

---

System/totp.30s.sh

-change menu bar title
-adjust parameter check
-adjust padding and set max account name and totp code length

fix visual items and parameter check

---

Messenger/bitbar-slack-team-notifications/README.md
Messenger/bitbar-slack-team-notifications/package.json
Messenger/bitbar-slack-team-notifications/slack-team-notifications.1m.js

Updated Slack plugin. Tests are failing but they seem to be from last merge.

Adding changes from main repo. Updated to v1.0.6

---

System/cpu-usage-kill.5s.sh

Shows top 3 consuming processes with opportunity to kill them.
no dependencies

New Plugin: CPU Usage, Kill process

---

Messenger/bitbar-slack-team-notifications/README.md
Messenger/bitbar-slack-team-notifications/package.json
Messenger/bitbar-slack-team-notifications/slack-team-notifications.1m.js

Feature request to have the option to not count all messages. Updated to v1.0.7

Adding option to only count mentions and DMs

---

System/microphone.sh

This little plugin mutes microphone on a single click.
On another click, it restores the microphone input level.

Mute microphone plugin

---

Cryptocurrency/nomics_bitbar.py

Adding v1 for nomics api bitbar plugin

Adding nomics_bitbar

---

Web/UptimeRobot/bitbar-uptime_robot.py

Displays the status and response time for all monitors available to an API key.

Add UptimeRobot plugin

---

Network/bandwidth-test.2h.sh

Added support for speedtest-cli installed via brew

---

System/ejector.5s.sh

Add mount/unmount capability

---

Tools/sensibo.60s.sh

This updates sensibo.60s.sh to the latest version, where the Fahrenheit temperature is correctly displayed.

Upgrade sensibo.60s.sh to the latest version (1.2.1)

---

Dev/GitHub/github-contribution.10m.rb

Fixes: https://github.com/matryer/bitbar-plugins/issues/1356

Skip loading bitbarrc if no section

---

Web/IrishRail/next_train.1m.sh

Irish rail updated their API so this script broke. This version fixes this

Fixed the Irish Rail check

---

Tools/PagerDuty/pagerDutyIncidents.30s.js
Tools/PagerDuty/pagerDutyOnCall.30s.js

More details in https://github.com/pedrofuentes/bitbar-plugins

Updated plugins to work with PagerDuty v2 API

---

Web/Feedly/feedly.rb

Modified URL in Feedly plugin! 
https://github.com/matryer/bitbar-plugins/issues/1223

Modify URL in Feedly plugin

---

Cryptocurrency/Bitcoin/mayer-multiple.sh

Hey guys,
Great project! I thought I add something to the community: here is a simple script that shows the current bitcoin's [Mayer Multiple](https://mayermultiple.info)
Screen:

Add Mayer Multiple plugin for BTC

---

Lifestyle/digital-zeitgebers.30m.py

A description of the plugin can be found [here](https://github.com/edwardqiu/digital-zeitgebers/blob/master/README.md). I'm open to any suggestions and thanks for your time!

Add digital-zeitgebers.30m.py

---

Time/CalendarLite.1m.sh

minor visual/conf improvement.

add optinal calendar icon to menu, update pic url

---

Dev/Gitlab/gitlab_projects.js

A complete rewrite of the original plugin, with feature parity.
Added bitbar node module as a dependency, which will automatically install if necessary.

Updated GitLab Projects plugin for API v4

---

Tools/desktop_cleaner.rb

Fail the script when a symlink found at Desktop. 
Ignore symlink for backup

Ignore symlink

---

Email/simple-gmail-checker.sh

`Gmail Checker Improved` plugin is great, but its dependencies' installation is hard. Simple Gmail Checker only uses sh with libxml2.

Simple Gmail Checker

---

Lifestyle/sureflap.1m.rb

Intentionally uses Net::HTTP from Ruby's standard library, so you shouldn't need any further dependencies.

Add SureFlap cat flap/pet door plugin

---

Time/ddate.30m.js

Hi @matryer,
I've created a plugin to show the current Discordian Date. It would be awesome to see in in the official list, so here's a PR 😃

Add Discordian Date plugin

---

Cryptocurrency/CoinbasePrices.sh

Add Dash to `CoinbasePrices.sh`

---

Dev/Docker/docker-disk.1m.sh

Plugin to show docker disk usage

add docker disk usage plugin

---

Lifestyle/taskpaper_current_task.29s.py

A simple script that displays the first task with a specified tag in a Taskpaper file.
I'm using it do display the task I'm current working for.

Taskpaper current task

---

Network/sent-received.1s.sh
System/cpu-load.5s.sh
System/launch-agents.10s.sh

Imgur is a more reliable image host than me

Use imgur for @rnkn plugins

---

Lifestyle/taskpaper_current_task.29s.py

Added better screenshot showing both BitBar and Taskpaper:

Taskpaper Current Task - add better screenshot

---

Weather/typerlc-weather.15m.sh

Add the plugin hosted here https://github.com/typerlc/bitbar-plugins to the Weather plugins

Add typerlc weather plugin

---

System/power_wattage.30s.sh

A simple plugin to get ac power adapter wattage.

Add plugin get ac power adapter wattage.

---

AWS/ec2-start-stop.1h.sh

Hi,
This is a new plug-in for you to start/stop EC2 instance.
It will load your instance list from your AWS profile automatically.
Thx.

Add AWS EC2 instance start/stop plugin

---

Tools/sensibo.60s.sh

This updates sensibo component, providing the latest version (1.2.2) which adds Climate React.

Update sensibo.60s.sh (v1.2.2)

---

Science/fah-score.1m.py

Hi there 👋 , this PR adds a script which displays Folding@Home score.
Folding@home is a distributed computing project for performing molecular dynamics simulations of protein dynamics.
https://foldingathome.org/
Thanks!

Add Folding@Home score plugin

---

Network/openfortivpn.sh

- Add a plugin to be able to connect/disconnect or track openfortivpn status by using fortivpn-config certificate file.

Add openfortivpn Bitbar plugin

---

Environment/covid-19_stats.15m.sh

Adding a new plugin I created to track COVID-19 in the United States.

Add covid-19_stats.15m.sh

---

Dev/Gitlab/gitlab_merge_requests.js

Adding a new plugin to allow display the status of currently assigned and reported GitLab Merge Requests.

add gitlab merge request bitbar plugin

---

Web/Instagram/social_media_stats.1h.py

Adding a plugin written in Python3, that shows YouTube subscribers, Facebook likes, Instagram and Twitter followers.

Add social media stats plugin

---

Games/steam-dashboard.1m.sh

Display online player count and track daily/weekly/monthly reviews of a Steam game. Please edit parameters.
https://i.imgur.com/hd7dRju.png

Steam Dashboard

---

System/AirPodsPower.sh

Shows case, left and right earphones percentages.
If they are not connected:
---

Add AirPods battery power

---

Dev/RescueTime/rescuetime.1h.py

urllib2 -> urllib
docs: 
https://stackoverflow.com/a/2792652/3281978
https://stackoverflow.com/a/28906913/3281978

fix: update to python3

---

Time/solar-time.1s.py

Image address

---

Tools/rsyncbackup.js

I created this plugin to make it easy to create backups based on 'rsync' that also shows some status and allows for some interaction by the user.  I've been using it myself for a few weeks, making small tweaks to get it in shape for a PR.
The plugin is more or less self-guiding.  Once you add it (along with the dependencies) it should give you an option to edit the configuration file.  Once you feed it a valid config, it should start running backups (either manually or scheduled, if requested).
Thanks for your consideration.

Added new rsyncbackup.js plugin

---

Lifestyle/Bear/bear-calls.sh

Hello!
I added a little bear script, and posted about it on the Bear subreddit 🤠 
https://www.reddit.com/r/bearapp/comments/j3qq7k/yet_another_way_to_create_templates_or_other/

added the first bear script

---

Messenger/slack-status.sh

This is a simple plugin, with a built in example, using curl and Statuscool, to set your Slack status.

Slack Status

---

Environment/covid-19_today.15m.sh

Compares daily change and daily average for one country. Modified version of covid-19_stats

Add covid-19_today.15m.sh

---

Weather/Foobot.10m.rb

Added plugin to display [Foobot sensor](https://foobot.io/) readings in the menu bar.

Added Foobot plugin

---

Finance/exchange-rates.5m.sh

Here is my plugin: https://github.com/makiftutuncu/exchange-bitbar

Add exchange rates plugin

---

Music/plex-status-improved-30s.py

This is a new and improved Plex Status bar with no dependencies (beyond python) and many new features:
* Supports Music, TV and Movies
* Supports multi user Plex Servers
* Shows device info when listening on something other than your Mac
* Written so that functions can be easily imported into other python scripts
It's easy to use, and very easy to modify in case there's some custom content on your server that doesn't fall within Music, TV or Movies.

New and Improved Plex Status Script

---

Tools/addnote.5s.py

- Changed icon 
- Made it so simply clicking on the icon brings up the Add Notes dialogue.

Change Icon & Single Click

---

System/Battery/watt-meter.20s.py

Update for macbook pro 16 inch

---

Weather/OpenWeatherMap/weather.15m.py

Not sure why this was replaced, would like to keep original credits for my work.

Weather source update

---

Dev/GitHub/github-contribution.10m.rb

edit github markdown regex and orm query

edit RE_CONTRIBUTION regex and contributions sql query

---

Lifestyle/ToDo/NotePlan3.15m.rb

To suit upcoming change in NotePlan3 to use #⭐️ as a priority marker.

Tweak priority_label

---

Music/fip.1m.sh

This plugin show the current song played by FIP (a famous musical french radio).
This scrip retrieve the information on the title currently being played (as well as the previous and next one) from the Radio France public API. Clicking on the track redirects to the associated iTunes page, for the current and previous track a Spotify search is available.

New Plugin : FIP (French Radio)

---

Messenger/slack-team-notifications.1m.js

- Update to latest API
- Fix timestamp for "Mark as Read"
- Add configuration for ICON and MAX_LENGTH
- Optionally show "No new notifications"
- Update scope requirements

Update slack-team-notifications to v1.1.0

---

Dev/Clubhouse/clubhouse.rb

This is a plugin to display your Clubhouse.io work and allow to quickly open tickets, associated branches and pull requests

Add clubhouse.io plugin

---

Sports/live_nba.1m.py

This plugin can show NBA game scores (including scores of quarters) in bar.

Add a plugin to show today's NBA game scores

---

System/screenshot.1d.py

static.md's API is non-functional and doesn't work.
Replaced it with Imgur's upload and this fully works!

Replace non-working Static.md with Imgur upload

---

.test.py
IOT/BMWcharge.15m.py

Hi,
this plugin will log into BMW's ConnectedDrive platform and display your car's charging status and ETA (while charging) or your remaining range.

BMW Charging Status plugin

---

Cryptocurrency/slushpool.5m.js

Plugin to see your existing miners/workers hash rate, confirmed/unconfirmed/expected rewards, and details about your workers in your macOs menu bar.

Added Slushbar, the Slushpool XBar plugin

---

System/Yubikey.30m.sh

Plugin that generates totp codes using yubikey and copy to clipboard, supports touch and touchless code generation.
Use ykman from /Applications/YubiKey Manager.app

Add a Yubikey plugin

---

Network/netstats.5s.sh

Also tweaks the logic so it's more robust and hides wifi stats when there is no wifi.

Update netstats.5s.sh with xbar variables

---

Web/hackernews.10m.py

For a preview of what this looks like: https://github.com/terror/bitbar-hackernews

Add hackernews plugin

---

Tools/aggregator.5m.sh

Check aggregator directory existence
Check if aggregator directory contains files

v1.1 of the aggregator plugin

---

Network/001-bandwidth_KBps_MBps.1s.sh

Display bandwidth in KB/s or MB/s

---

Email/unread.1m.sh

GH repository here: https://github.com/harrisonpage/unread
Tested on my desktop, seems to work!

Plugin to show unread emails from Mail.app

---

Dev/Gitlab/gitlab_merge_requests.js

Adding in some bugfixes I forgot to add earlier and upgrade to use xbar variables (shiny :D, and I don’t have to forget to remove my gitlab token anymore)
Should fix the issue raised in https://github.com/matryer/xbar-plugins/issues/1607

Upgrade gitlab_merge_requests to work with xbar

---

Tools/pass.sh

* Show list of your password from `pass` ([the standard unix password manager](https://www.passwordstore.org/))
* Copy to Clipboard by click an item in list

add password store for xbar plugin

---

Music/ksing.1d.py

KSing is a karaoke mobile app from China, which allows users to sing and upload their own songs to share with others, but unfortunately there is no way to listen to them on the Mac.
This plugin helps people who want to listen to music from KSing on the Mac. You can click the help in the plugin to see the detailed usage. 
Later, I will give a readme of the English Version (although I don't think there may be any English users)

Add KSing plugin

---

Music/spotify.10s.sh

- Merged changes from v1.3 (#1542)
- Add `CYCLE_TRACK_ARTIST` option to scroll through text longer than truncated text
- Fix for quotes in lyrics search
- Updated metadata and xbar params (`bash` -> `shell`)

Update spotify.10s.sh to v1.4

---

Network/ssh.sh

Added Terminal=true
use /bin/zsh

Updated for xbar v2.1.16

---

Cryptocurrency/okex_ticker.10s.py

Currencies can be configured. See the screenshot bellow:

feat: a new plugin to show price ticker from OKEx

---

Time/pomodoro.1s.sh

Fixes https://github.com/matryer/xbar-plugins/issues/1650

Define TMP_DIR in pomodoro plugin

---

Dev/GitHub/notifications.30s.py

Fixes https://github.com/matryer/xbar-plugins/issues/1634

Display char for 0 notifications in GitHub plugin

---

Time/pomodoro.1s.sh

Pomodoro: Add missing sound for disabled mode

---

Music/ksing.1d.py

- Change text encoding from UTF-8 to GB2312 (Chinese)
- Add **open in browser** option
- Add **open cache folder** option
- Code lint
- Modify songList update logic
- Long time test without bug

Fix some text encoding problems and add more features.

---

Web/hololive.5m.rb

Add hololive streams plugin that accesses Holofans API.

Add hololive plugin

---

Dev/ntl-site-status.1m.js

This plugin puts a netlify icon in the menu bar that changes color based on if your site is deployed, building, or had an error in its last build.
[repo](https://github.com/joshatoutthink/ntl-site-deploy-status)

Add Plugin: Netlify Deploy Status

---

Tools/Slack/slack-team-notifications.1m.js

- Replace `bash` param with `shell`
- Update references to bitbar with xbar
- Use `XBARDarkMode`

Update slack-team-notifications.1m.js to v1.1.2

---

Dev/Gitlab/gitlab_glance.15m.py

Show review and authored MRs as well as assigned issues for current user for upcoming milestone in the menubar.
https://user-images.githubusercontent.com/1748044/125606649-cbb41156-0251-43c9-a268-37b4897070bc.mov

Add GitLab Glance plugin

---

System/ntfs.1d.sh

This plugin is used to re-mount read-only NTFS disks in read-write mode.
more description is here: https://xfangfang.github.io/025

Add NTFS Mounter Plugin

---

Lifestyle/taskwarrior.4m.py

Changes necessary for supporting the script with Python3. Also tested under Python 2.7 and all worked as expected.

Added support for python3 code conventions

---

Dev/GitHub/notifications.30s.py

The python2 is now outdated and using it produces the warning in macOS. Also formatted with black, for consistency.

Update to python3

---

Dev/noti.1m.py

Noti is a Mac OS X menu bar plugin to show the status of pull requests (merge requests). Currently it supports Github and Gitlab.

Added noti plugin

---

Dev/meta_package_manager.7h.py

Upgrade mpm plugin to latest v4.2.0.

---

Finance/awin-sales.60s.py

This adds a plugin that will check your daily publisher statistics on the awin.com platform.
Repo can be found here:
https://github.com/pschoenmakers/xbar-awin

Add a plugin that will check daily publisher statistics on the awin.com platform

---

System/microphone.sh

Update microphone.sh to use usr/bin/env

---

Tools/pass.sh

Sync and use [v1.0.3](https://github.com/ri7nz/x-pass-plugin/releases/tag/v1.0.3)

feat(pass): use v1.0.3

---

Web/ProductHunt/producthunt-tech-hunts.1d.py

This pull request migrates the [Product Hunt - Today in Tech](https://xbarapp.com/docs/plugins/Web/ProductHunt/producthunt-tech-hunts.1d.py.html) plug-in to Python 3.

Migrate Product Hunt plug-in to Python 3

---

Network/pivpn.1m.php

Show clients created from pivpn installation and status.
Need install https://github.com/alexandregz/bitbar-plugins-alexandregz/blob/master/pivpn/api.php on pivpn machine (instructions in comments and README)

Add plugin pivpn

---

Dev/GitHub/notifications.30s.py

- Fix /issues/1780
- Fix `TypeError: a bytes-like object is required, not 'str'`
- Add `Discussion`, not sure how to add the image 🙈 I wanted to use this one: https://primer.style/octicons/comment-discussion-16
- Add also `CheckSuite`, same problem here with the image. https://primer.style/octicons/play-16, not sure why but `CheckSuite` don't have `href` so link is not working 😞

001-notifications.30s.py: fix small bugs and add discussion

---

Dev/GitHub/merge-freeze.5m.rb

Extension for GitHub Marketplace app Merge Freeze:
https://github.com/marketplace/merge-freeze

add Merge Freeze plugin

---

System/swap-usage.1m.sh

Very simple swap usage indicator bash script

Added swap memory usage indicator

---

Network/SSH-Remotes.1d.sh

Hi, added a small Plugin for quick SSH connections.
This Plugin makes it easier to define your remotes in the script and lets you choose between Terminal and Hyper.
Cheers.

Adds the SSH-Remotes Plugin in Networking

---

Cryptocurrency/Monero/monero-usd-kraken.30s.sh

Add decimal variable to monero-usd-kraken plugin to make it possible to configure value to be shown with any number of decimal places.

Add decimal variable

---

Sports/worldcup.1m.php

- Updated description
- Changed API address
- Changed code for new API structure
- New flags and Teams
Signed-off-by: dgold <dgold@ascraeus.org>

Update for WC 2022

---

Tools/yabai_skhd.1s.sh

Query attributes hav been refactored since yabai release 4.0.0
https://github.com/koekeishiya/yabai/issues/775

Update yabai/skhd helper for yabai 4.0.0+

---

Weather/aqi.15m.sh

I'd like to improve the UI a little bit and then found out that the aqicn.org has some nice graphs and here is what it looks like now:
and it doesn't depend on the `jq`, since we're dealing with the HTML tags. 
TODO: add donation info from aqicn.org to support them.

remove dependencies and enhance the UX of the Air Quality Index plugin.

---

Tools/Slack/slack-team-notifications.1m.js

* Fix issue with "Mark all as read" #1773

Update slack-team-notifications.1m.js to v1.1.3

---

Cryptocurrency/Bitcoin/mempool.sh
Cryptocurrency/mempool.space

Adds the ability to see Bitcoin transaction fee stats in real time...
I did another Pull Request, but nobody has replied or said anything, so I tried "Add a File" this time. Would be nice if someone pulled this so other people could enjoy it.

Add support for Mempool.space

---

Finance/mintable.1h.zsh

Adding a Plugin for [Mintable](https://github.com/kevinschaich/mintable), an open-source tool to automate your personal finances – for free, with no ads, and no data collection.

Add mintable.1h.zh plugin

---

Dev/podman.5s.sh

Adds a simple plugin for [Podman](https://podman.io/) 
Current features:
- Start/stop Podman machines
- Allow users to update Podman via Homebrew when an update is available

Add plugin for podman

---

IoT/evcc.10s.rb

Shows the status of your local evcc instance. Displays your home energy situation (production, consumption) and the charging situations for your wallbox(es) and car(s).
More information on the evcc can be found here: https://evcc.io

Add new plugin: evcc (solar ev charging)

---

Dev/Wakatime/wakatime.1m.js

This plugin gets your coding time from Wakatime site.

Wakatime plugin

---

IoT/wled.1m.js

Totally open to new and better ways of doing this, but this has seemed to work for me for a few weeks now!

Added super basic WLED plugin

---

Dev/GitHub/github_work_list.1m.mjs

My company moved from gitlab to github so I re-wrote my plugin to work with github to keep the same workflow.

Add new plugin for github version of gitlab_merge_requests.js

---

Dev/Gitlab/gitlab_glance.15m.py

This PR updates GitLab Glance plugin with the following enhancements;
- Use system python3 which is located at `/usr/bin/python3`.
- Remove `requests` module dependency and use `urllib`, this is a major improvement as earlier user had to install `requests` manually to be able to use the plugin.
- Escape pipe symbol with identical Unicode symbol since pipe is also a separator.
- Updates GitLab logo to use the redesigned logo.
- Use [GitLab SVG library](https://gitlab.com/gitlab-org/gitlab-svgs) icons for menubar items instead of emojis.
- Run the plugin code through python formatter for better readability.
|**Before**|**After**|
|----------|---------|
|<img width="594" alt="image" src="https://user-images.githubusercontent.com/1748044/198813827-ebe6a882-e8f4-4339-8469-497e40a67443.png">|<im …

Update GitLab Glance plugin

---

Weather/DarkSky/weather.15m.py

I could not make xbar to work with those placeholders, but real emojis work fine.

Replace icon placeholders with real emojis

---

Dev/GitHub/github-review-requests.5m.py

Stuff I thought that I had to look up that I thought would be useful to others:
* Indicate which permissions are needed when creating the Personal Access Token
* Direct link to the page to create Personal Access Tokens, i.e. [https://github.com/settings/tokens]()

Updated documentation for github-review-requests.5m.py

---

Travel/commuter.365d.py

Better error handling 
Add debug.txt to see result of API call
Change commuter icon

Better error handling

---

Cloud/scaleway.sh

Add Scaleway instances status/start/stop plugin written in bash. Located in Cloud/scaleway.sh

Add Scaleway instance management plugin

---

network/uRadMonitor.30s.sh

Allow displaying in real time the current radiation detected by Geiger counter from uRadMonitor.
https://www.uradmonitor.com

Monitor radiation from a uRadMonitor device

---

Dev/Buildkite/buildkite.1m.sh

Add a plugin to show recent Buildkite builds:
Plugin repo: https://github.com/edwardsnjd/bitbar-buildkite

Add Buildkite plugin

---

Tools/PagerDuty/pagerduty_incidents.1m.sh

This plugin will display open Pagerduty incidents assigned to a user.

Add Pagerduty plugin

---

Dev/uptimekuma.30s.py

I created a plugin that reads status from UptimeKuma, an open source alternative to UptimeRobot ( that already have a plugin here).

Add uptime-kuma plugin

---

Lifestyle/deathTimer.5m.py

Update the script to use Python3

Python3 update

---

Tools/addnote.5s.py

This pull request updates the plug-in for Python 3, 4fddc4c7543a9f5ca02fb4f50280d58db9d7b63d was reverted because it didn't seem to work under BitBar either.

Update Add Note for Python 3

---

Tools/whos-home-unifi.1m.py

See https://github.com/DouweM/xbar-whos-home-unifi for screenshot and more details.

Add 'Who's Home? (for UniFi)'

---

AWS/pipeline-status.1m.py

Adds a AWS plugin that shows the status of a CodePipeline.
Configure pipeline name in the plugin settings.

Add AWS CodePipeline Status plugin pipeline-status.1m.py

---

Cryptocurrency/miner_stat_fetch.1m.py

-Get Current hashrate
-Get Average hashrate
-Get Incomr from last hour

Crypto Miner statistic fetcher

---

Lifestyle/qurandaily.1d.py

This plugin displays a verse from the Holy Quran.

Add new plugin Quran Daily

---

Tools/yabai-viewer.1s.py

Add an visualiser plugin for yabai, written in python. Shows all spaces, where spaces are on your displays, what applications are open on your spaces, and what space and application is currently focused.

Add yabai-viewer plugin

---

Tools/bitbarDockerContainers.1m.py

List all docker containers
Stop all docker containers
Start/stop an individual container
Open Terminal with container information

Added docker plugin

---

Games/jackpot.6h.py

I wasn't 100% the category but "Games" I guess is right? Finance certainly didn't seem correct. This displays the current Mega Millions and Powerball jackpots. It turns green if the jackpot size is over $200M. The menus link to the respective lottery web sites.
Feel free to re-categorize as you feel appropriate.

Add new plugin:  jackpot

---

AWS/ec2-start-stop.1h.sh

- Added AWS_CLI_REGION variable
- Fixed nested menu display
- Added `/opt/homebrew/bin` to PATH (common for `jq`)
- Replaced text menu item with icon

Updated ec2-start-stop plugin

---

System/unmount.10.js
Tools/ejector.10s.js

I realise that there is already an Ejector plugin, but this one is simpler, plays nicely with dark mode and is only present when there are volumes mounted.

Add unmount plugin for unmounting/ejecting volumes

---

Lifestyle/librelinkup.1m.py

using LibreLinkUp API to display GCM values

Add LibreLinkUp Plugin

---

Tools/dev-toolbox.1h.sh

Add nifty utilities for everyday developer use in the menu bar. 😊

Add DevToolbox plugin 🛠

---

Dev/GitHub/github-review-requests-TS-5m.ts

A new version of the Github-Review-Requests by @bogdal. This one is entirely written in TypeScript and uses Deno as a Runtime environment.
The new version has the following updated visuals:
* Biased color coding
* New fonts
* Emojis to determine PR status
* PR status
* Conflicted PR
* Removes PRs that are approved and have no conflicts

Github-review-request overhaul (powered by TS)

---

Web/toggl.1m.js

Fixes toggl api url
Fixes missing quotes for path
Fixes Homebrew path

Fix toggl workflow

---

Dev/Homebrew/brew-services.10m.rb
Dev/Homebrew/brew-updates.1h.rb

This adds the latest [changes from my dotfiles](https://github.com/jimeh/dotfiles/compare/c7ea3d186a2e2c502c05fbe73d12685006aa8848...14c58e849f7c986eb8ed336a5e786e1c17ca16cc).

Update Homebrew plugins to fix issue on Apple Silicon Macs and add Greedy option

---

Dev/AzureDevOps/build-status.1m.js

Azure DevOps plugin showing status of the latest build of a given pipeline using https://learn.microsoft.com/en-us/rest/api/azure/devops/build/latest/get?view=azure-devops-rest-5.1

Add Azure DevOps plugin build-status.1m.js

---

Lifestyle/librelinkup.1m.py

* cleaned up header
* added auth error output
* fixed high/low color

LibreLinkUp - some Cleanup and high/low display color fix

---

Dev/Homebrew/brew-services.10m.rb

Move settings to it's own menu, change started/stopped emoji's, as the
green/grey checkmarks are now used for settings.
Also refactor Xbar::Config and and Brew::Common classes a bit to make
them more generic, and a few other improvements copied over from the
brew-updates script.
---
This pulls in the latest changes to the brew-services plugin from my [dotfiles](https://github.com/jimeh/dotfiles/tree/main/xbar).
**Before:**
**After:**

feat(Dev/Homebrew/brew-services): improve settings and style

---

Network/zerotier-status.1s.py

Python3 plugin to view (and manage) Zerotier Network connections.

Added Zerotier Status Plugin

---

Travel/airspace.5m.py

This PR adds the Airspace plugin to /travel. Airspace shows a list with clickable elements containing general information about flights traveling in the airspace above the user's location. Information about how it works and motivations can be found on the repo's [readme](https://github.com/victor-nazario/airspace).

Adds airspace.5m.py plugin to /travel

---

Dev/ips.30s.sh

Plugin to allow displaying and copying the local and external IP address of the device.

Add IPs plugin to show local and external IP

---

Time/DayAndNightClock

A clock that can show moon phase when it is night time and show the calendar.

New plugin

---

Tools/rclone-mount.1m.sh

A plugin to mount and unmount rclone remotes.

rclone-mount

---

Time/worldclock.1s.sh

- Update plugin to use xbar variables with default zones. Allows issue author to add their timezone via the variable.

Issue #964 - World Clock additional zones

---

Dev/GitHub/github-contribution.10m.rb

- Apply patch from geekness provided in issue thread.
- Use xbar variables to configure the username and max contributions. Clean out code around having these in an INI file.

Issue #1550 - github contribution plugin issue

---

CONTRIBUTING.md

Add the `disabled` option to the documentation

add the disabled option

---

Web/beeminder_one_goal.1m.py

Hi, just sharing this, feel free to merge it or not, I don't mind :) 
I keep my plugins at: https://github.com/tadamcz/xbar-plugins

Add Beeminder (for single goal)

---

Network/iTermSshMenu.sh

Provides a simple menu of ssh hosts when clicked on opens a new ssh session in terminal

iTerm SSH Dropdown Menu

---

Environment/solaredge.5m.py

Adds menubar support for battery percentage if battery is present.
(Single battery only)

Update SolarEdge Plugin - Add battery Support

---

Environment/solaredge.5m.py

Tidies up the code a little - makes font size configurable and adds in current usage from the inverter and from the grid. This is about as far as this plugin can go for now without adding in EV Charging. 
NOTE: Will revisit when I have an electric car - already have the inverter.

Final Commit

---

Environment/solaredge.5m.py

- Fixed a bug where battery charge power was getting added into total DC Output, this should only be the case if the battery is in a discharge state
- Removed Environmental Impact calculation and replaced with SolarEdge stats
- Added indicator to show if battery is in charge, discharge or idle state.
- Made all optional or configurable elements xbar variables.

Use SolarEdge Environmental Figures

---

Lifestyle/librelinkup.1m.py

Update Libre LinkUp Header Version
Add Message for Status == 4 -> reaccept TOS
Fix low trigger point

Bump LLU Version, add TOS check, fix low trigger

---

Finance/yahoo_stock_ticker.10m.py

Yahoo Stock Ticker: change URL to avoid auth and update response parsing

---

Weather/emojiWeather.30m.js

- Replace `request` with `axios` library.
- Fix emoji generation. Based on the documentation, the weather ID to emoji calculation and list of emojis itself was not in sync.
- Move city and API key to xbar variables.
- Update shebang to use `env` pattern.

Issue #1968 - 001-emojiWeather.30m.js: request module has been deprecated

---

Time/worldclock.1s.sh

- Use default macOS Monaco font for display
Closes #1881.

Issue #1881 -  001-worldclock.1s.sh: use monospace font #1881

---

System/macosnightshift.1h.sh

A quick xbar tool to toggle MacOS Nightshift with less clicks.

Added nightshift toggler

---

System/systeminfo.1s.sh

- Adding new plugin on behalf of author.

Issue #1973 - Adding a New System Information Plugin

---

Dev/servicemonitor.1m.py

This version improves the previous plugin.
* Fix small bugs
* Add issue logs: The menu shows the last issues.
* Display error messages: It is possible to open the EditText with the error message from the menu.
* Add notifications: Popup a notification when a service fails.

Service Monitor v1.0

---

Network/wifisignal.sh

Fix occasional error when wifi status comes back in 7th state.

Fix "color: unexpected hex string or named color" error

---

System/DarkModeToggle.sh

Since it's supposed to change the whole appearance, a notification is a bit redundant

Remove Dark Mode Toggle notifications

---

Lifestyle/librelinkup.1m.py

Hi, I made this changes for my own usage on the `LibreLinkUp Status` plugin. It can be useful to more people.
I don-t know how to create the UI to let the users input the constants. I just left them hard-coded on the top of the file, at least users will be able to change the code. Feel free to make a second PR adding the UI.

Improve `LibreLinkUp Status` plugin: Display elapsed time since last reading + customizable range + refresh button + error handling + refactor

---

IoT/BMWcharge.15m.py

* Support for current bimmer_connected API
* Use user-friendly xbar.var configuration
* Have more user-friendly setup error

Update BMWcharge to 2.0

---

Web/leetcode_reminder.5m.py

Added a new script that motivates and reminds you to complete your daily coding challenge on Leetcode.
[README](https://github.com/zihengjackchen/xbar-scripts/blob/main/leetcode_reminder/README.md)

added leetcode_reminder

---

Music/swinsian.10s.sh

Add's the Swinsian music manager/play current track playing plugin

Add Swinsian plugin

---

Politics/congress.1h.R

(First Plugin to be built in R!)
Tracks US congressional bill action and individual members of the congress. 
Requires ProPublica Congress API Key.

Tracking Congress (First plugin using R)

---

Lifestyle/USCIS_CaseStatusUpdates.15m.sh

This script checks every 15 minutes on the USCIS
(United States Citizenship and Immigration Services)
Website https://egov.uscis.gov/casestatus/landing.do
for your Case ID and notify you when there is an update.

Add USCIS_CaseStatusUpdates.15m.sh plugin

---

Dev/meta_package_manager.7h.py

More documentation available at: https://kdeldycke.github.io/meta-package-manager/bar-plugin.html
Changelog:
* Always call `mpm --version` without color.
* Increase robustness of `mpm` version parsing, whether its colored or not.
* Upgrade minimal version of Python to 3.8.0.
* General code linting, typing and formatting.

Upgrade to Meta Package Manager plugin v5.14.1

---

Lifestyle/nightscout.1m.sh

Added xbar variables and added support for use of API token from nightscout

add vars to nightscout and API Token

---

Finance/001-options.1h.go

Get an API key and put it here (sign up for one for free at https://www.yahoofinanceapi.com). Input some variables in the file. Then ```go build``` the file in the plugins folder and rename.

Newoptionsquoteplugin

---

Time/toggl.10m.sh

`Toggl Xbar` wasn't very useful, updated to `Toggl Multi-Workspace`, apologies for not catching this earlier.

Update Toggl plugin title

---

Weather/sunrise-sunset/sun.1m.py

some improvements:
- how many hours up until next phase
- small indicator next to the number for minutes
- if <1h, shows mins
- show wave of % sunlight throughout the year
- other improvements, e.g. absolute time, ratios, etc

sunrise-sunset: part 2

---

Lifestyle/zoom_onair.15s.py

Starting with python version 3.12 homebrew installs of python are marked as externally managed and require the '--break-system-packages' flag in order to install extra modules. Try installing without the flag first in the hopes that someday this will run in a virtual env, but if/when that fails try again with the flag.
Update message output to put all messages in an array to ensure that the title info remains on the macOs menu bar and error or other info is displayed in the drop down menu.

zoom_onair plugin: update install function and message generation

---

Time/timetable.1m.py

It's a menu bar plug-in to display the current event from a customizable timetable.
The user only needs to define the daily timetable as a `.csv` file and configure the path to the CSV file in the script. The plug-in will display the current event in real time on the menu bar. The pop-up window will show the whole timetable pre-defined in the CSV file.
The csv file is required to be formatted as below:

Timetable v1.0

---

Time/timetable.1m.py

- Now support emoji
- More configurable features: font, font size, remaining time display
- More friendly error prompting
Details: [project repo](https://github.com/cabinz/xbar-timetable)

[New] Timetable 2.0

---

Web/rss.15m.php

- Update shebang to look for PHP in path and in Homebrew locations.
- Update commands to work with any directories containing spaces in their name.
Credit to @KenSmz for the patch.
Closes #1851

Issue #1851

---

System/app_use_cpu.1m.sh
System/google_chrome_use_cpu.1m.sh

Show CPU usage from Google Chrome; hardcoded, but you can use param APP to change this. Also you need to change ICON manually.

google chrome CPU usage

---

System/app_use_cpu.1m.sh

my mistake, sorry.
My previously PR #2053 had hardcoded my RAM amount (24GB) so I put variable VAR_RAM to use with other values 😇

variable amount of your RAM (previously hardcoded to 24G, my value O:-)

---

System/rebootreminder.1h.sh

Move xbar.image to https://lawtalker.github.io/rebootreminder/rebootreminder.jpg

Update rebootreminder.1h.sh to v1.2.1 (change URL for xbar.image)

---

Network/got-internet.2s.sh

I renamed my account, but this still points to the old one. You can see the rename on your own site: https://xbarapp.com/docs/contributors/bfred-it.html
I hope that this page on the website will also be dropped/changed after this PR is merged

Update author of script

---

Environment/electricitymaps.5m.py

Hello 👋 
This PR creates a new plugin from the Electricity Maps API (docs.electricitymaps.com) showcasing how clean electricity is in the user's location. It builds upon the old and outdated [CO2 signal plugin](https://github.com/matryer/xbar-plugins/blob/c85e2c46d3c593e22b1b02d10e91c26f74f0c888/Environment/CO2-Signal.10m.py), which is using a deprecated API.
Feedback much appreciated!

Add Electricity Maps integration

---

Web/bitbar-uptime_robot.py

Added Author and separate Total Download and Total Listed Download counts.
Updated the Screenshot
Fixed Shabang

Updated NugetDownloadCount

---

Lifestyle/librelinkup.1m.py

The current version is always crashing, this change is needed to fix it.

Update "LibreLinkUp Status" because API to get data changed

---

Network/vpn-next.2s.sh

Adding new plugin for status display and control of Macos VPN profiles via Network Extensions. 
https://github.com/anandi108/xbar_vpn_next

Adding new plugin for status display and control of Macos VPN profiles

---

Network/vpn-next.2s.sh

Updated version v1.1 of Network/vpn-next plugin. Making plugin fully configurable through xbar.var parameters.

Updated version v1.1 of Network/vpn-next plugin

---

System/lastpass.py

Utilizes the LastPass CLI to make user's vault available in xbar.

Add Lastpass plugin

---

Environment/carbon-intensity.15m.js

Added 24 hour carbon intensity graph
Several usability and documentation updates

Release version 1.3

---

System/memory_pressure.20s.py

CHANGES:
- Uses `memory_pressure` command to fetch memory statistics.
- Calculates memory pressure based on free memory percentage.
- Displays memory pressure with colored icon (green, yellow, red).
- Shows memory pressure, free pages, and used pages in detail.

feat: creates `memory_pressure.20s.py` to display system memory pressure

---

AWS/profile-changer.1s.sh

Easily switch between multiple AWS CLI profiles

new plugin: AWS profile switcher

---

personal/homecoming.1d.sh

I hope more home sick people can add this so they feel better about going home soon ://

Add Homecoming Countdown plugin

---

Cryptocurrency/bitso-prices.10s.sh

Show some crypto prices from Bitso in USD

Displays BTC, LTC, ETH, XRP and BCH prices from Bitso either in USD or MXN

---

AWS/profile-changer.1s.sh

simplify my profile change script
* add shells for running in background without aws cli
* remove unused scripts

fix: profile changer

---

Dev/GitHub/github-pr-list.10m.ts

Add github pr review list plugin
