matryer/xbar-plugins

- README.md
- Weather/GeoIPWeather.15m.rb
Plugin detects your current GeoIP and gets the weather based on that data. It should work worldwide. Units are configurable at the top of the file.
Updated Plugin README accordingly.
> Added plugin to get the weather at your current detected GeoIP location.

- System/real-cpu-usage-chart.10s.sh
as it doesn't like small decimals (e.g. ".2" when $IDLE is "99.8").
> Fix real-cpu-usage-chart - pass integers to spark

- README.md
My name was apparently removed accidentally by another contributor ;) https://github.com/matryer/bitbar/commit/c15301be16a89e14df0ddac0d737307e44416457
> Restore name in README.md

- Dev/Docker/docker-status.1m.sh
- Switched the shebang to `bin/env sh` over `bash` for better
compatibility with all POSIX environments.
- Run file through shellcheck, which threw up some lint errors,
which have been fixed.
- `docker-machine env` has been passed the `--shell` flag, to
specify the shell environment explicitly. Before it was relying
on the user's shell being `bash` which is obviously not always
the case.
> Dev/Docker/docker-status: lint & fix bugs

- Dev/GitHub/notifications.30s.py
- README.md
This bitbar plugin fetches your GitHub notifications through the notifications API, and lists them as menu bar entries. If you have notificarions you get a blue dot, otherwise you get a dim grey dot. Each menu item is clickable - and takes you to the issue or pull request that the notification was for.
See screenshots:
No notifications!
Many notifications!
If you want to test what notifications look like, change like 12 (`url =...`) to have the query string `?all=true`.
> Dev/Github/notifications: initial implementation

- Dev/GitHub/notifications.30s.py
As in `pulls`, `commits` has to be substituted for `commit` to go directly to the notification
See the difference between these urls
```
https://github.com/driftyco/ionicons/commit/57a7bf240f7dd42ce8c1b09b2f6bf3708d4a0c2a
https://github.com/driftyco/ionicons/commits/57a7bf240f7dd42ce8c1b09b2f6bf3708d4a0c2a
```
cc @keithamus
> Support commit notification

- Time/fuzzyclock.1s.py
All time formats which added 1 to the current hour resulted in an error
between midnight and 1AM because 13 is not in the number-to-word
translation dict because the clock is 12 hour. Extra modulos have been
introduced to fix this.
The same commit also fixes an inconsistency in capitalisation, because I forgot to separate that out.
> [fuzzyclock] Fix error between 00:30 & 01:00

- Dev/Docker/docker-status.1m.sh
This commit gives each menu entry some clickable interactivity:
Docker machines which are on (and highlighted in green) - when
clicked - will be shut down (and subsequently all of their containers
will be stopped). If they are off (the ones highlighted in red) they
will be booted up.
The containers listed per machine now use tree like UTF-8 symbols to
better show their connection to their respective machine. In addition,
when clicked, they will be shut down. There is no concept of a
"non-running" container within this plugin, nor really with Docker, and
so there isn't an option to start containers up.
In addition to this, a small change has been made to the icon -
`dropdown=false` - to prevent the anchor icon showing up in the menus.
> Dev/Docker/docker-status: clickable entries

- Dev/Homebrew/brew-updates.1h.sh
Prevent the update count appearing in the dropdown, and instead
offer a clearer "Update all" option.
Switch from `` to $() to appease shellcheck
> Dev/Homebrew/brew-updates: lint & optimise

- Lifestyle/todo.30s.sh
This is useful when there are empty lines at the end of file, etc.
With this fix, these empty lines are not added to the todo count.
> Ignore blank lines in todo list

- Finance/currency-tracker.1m.py
- System/Battery/battery_cycles.12h.sh
Was wandering on the other PRs and I found a post from @keithamus about ShellCheck. Thought I should've test my scripts before opening my PRS.
So I tested my battery-cycles Bash script and my currency-tracker Python script through online lint testers ( www.shellcheck.net and www.pep8online.com ) and corrected them.
That's not a **big** fix, but I thinks that's necessary.
> Spellcheck & Python lint

- README.md
- System/power_status.15s.sh
A simple bash script to see the current power supply (battery or ac), and power settings.
> Added Power Status plugin, to see both power source and settings

- Dev/RescueTime/rescuetime.1h.py
* Add metadata
* Use the default urllib packages to remove the old hacky version using
a vendor requests library
* Add documentation regarding API key management
* Fix the labels (Distracting, Very Distracting) to match what
RescueTime uses
See matryer/bitbar#45
> Rescuetime updates

- Network/ssh.sh
Fix hashbang line.
Ignore wilcard host definitions so that all displayed results are
clickable ssh config entries in bitbar.
> Fix hashbang and ignore wildcard Host defs

- Weather/Wunderground.30m.rb
Adds support for the new metadata mechanism used by https://getbitbar.com.
> Add metadata to Weather Underground plugin

- Weather/Wunderground.30m.rb
Adds support for three new menu entries that open some web links:
* Forecast page
* Station historical data
* Google map of the station's reported location
> Forecast and other links for Weather Underground plugin

- Network/ping.10s.sh
A quick fix to show the same skull-and-crossbones character in the dropdown for any individual connection that is dead:
> Ping time script: indicate individual dead connections in dropdown.

- Finance/teller-track-spending.1h.sh
Track spending at a UK bank via the menu bar.
There are a couple of dependencies to this.
1. An account at Teller.io.
2. [teller-cli](https://github.com/sebinsua/teller-cli) setup on your machine.
3. `pcregrep`
[This is what it looks like.](https://twitter.com/nouswaves/status/684396522675527680).
> Track spending at a UK bank via the menu

- Finance/teller-track-spending.1h.sh
> Make teller-track-spending executable and give human readable name

- Dev/GitHub/notifications.30s.py
I added support for fetching **GitHub:Enterprise** notifications. For those of us that use both **GitHub.com** and an enterprise instance, notifications from both places will show up (rather than running a second instance of this plugin with GH:E modifications).
If a user doesn't define a GH:E token and API, that section won't show up.
> Add GitHub:Enterprise support to GitHub/notifications.30s.py

- Dev/Jenkins/jenkins-multiple-projects-status.1m.sh
Project names with spaces were breaking the curl.
> Adds support of projects containing spaces

- Finance/gfinance.5m.py
Displays stock tickers from Google Finance, and colors red or green based on where they are trading for the day.
> Added Bitbar plugin for Google Finance Stocks

- System/webpack-status.1s.sh
This plugin, in combination with [BitBar Webpack Status Plugin](https://github.com/Fire-Dragon-DoL/bitbar-webpack-status-plugin) allows to display the current status of webpack build (success/failure/in progress). Very helpful if you are checking the browser right after saving a file and don't want to go back to the terminal to see when the compilation succeeds (Typescript is quite slow).
> Webpack Build Status Plugin

- Time/timezone.5s.sh
I kept changing the timezone to `Australia/Melbourne` and it wasn't working. Finally realized the variable was case sensitive.
> Make Time_Zone and TIME_ZONE variables match.

- System/cpu-temperature.5s.sh
- System/fan-speed.5s.sh
Contains two scripts:
* One for displaying CPU temperature, configurable to Celsius or Fahrenheit also supports warning icon on set threshold
* One script for displaying fan speeds readings, multiple fans supported (labels optional, see script)
Depends on smc binary http://www.eidac.de/smcfancontrol/smcfancontrol_2_4.zip
> Add scripts for showing current CPU temp and fan speed readings using SMC

- System/uptime.1m.sh
uptime happens to have several different kinds of output, I'll list some examples:
> 22:49  up 24 secs, 2 users, load averages: 8.37 2.09 0.76
[ ↑ 24 secs ]
> 22:50  up 1 min, 2 users, load averages: 5.59 2.39 0.95
[ ↑ 1 min ]
> 23:39  up 51 mins, 3 users, load averages: 2.18 1.94 1.74
[ ↑ 51 mins ]
> 23:54  up  1:06, 3 users, load averages: 3.67 2.57 2.07
[ ↑ 1 hr, 6 mins ]
> 16:20  up 120 days, 10:46, 3 users, load averages: 1.21 2.88 0.80
[ ↑ 120 days, 10 hrs, 46 mins ]
> Fixed uptime to work with all the possible outputs

- System/clipboard-base64-encoder.sh
This is a plugin for bitbar to take the current entry from pasteboard in OSX (a.k.a. clipboard), encode it with [BASE64](https://en.wikipedia.org/wiki/Base64) and put it back into the pasteboard.
> Add plugin to encode current clipboard entry w/ BASE64

- Lifestyle/SaveToLinkPack.1h.rb
This plugin adds support for saving the current web page to a Linkpack folder.
It's not imperative that you use this with Linkpack, I just wrote this to fill the gap of using Linkpack with Safari (no Safari browser extension).
[Linkpack](https://linkpack.io) for those interested.
There is a known kludge with the "Open Directory" menu item. Due to the restriction of `open`, one cannot call it from an NSTask (or at least that is my understanding). The workflow works well enough for me, as I don't have to often visit the directory.
— Taylor
> Added plugin to save the current webpage to Linkpack/disk.

- Music/spotify.10s.sh
I found some very long track and artist names taking up my whole bar.  This change truncates long ones in the menubar, and leaves the full display when open if you're curious.
> [Music/Spotify] - Truncate long track and artist names

- System/usbInfo.10s.py
Previously color was hardcoded in white, which only shows in osx dark mode. Now shows in both mode.
Also opening System Information App on clicking a device
> [UsbInfo Plugin] fix color and open System Information on click

- Dev/Homebrew/brew-updates.1h.sh
Currently the number of updates available doesn't refresh after you make a change (ie click Upgrade All or upgrade a specific package). You have to wait for the cron to fire again or manually refresh once the update is done.
This changes it so it refreshes after brew completes your update. The downside is that you can't see what the terminal is doing, and so if something went wrong for some reason you wouldn't notice.
IMO this is better (it's what I use locally) but that's personal preference.
> Refresh count of brew updates after click

- Time/watson.1m.sh
A simple script which displays Watson's status (project name, started time and tags)
- http://tailordev.github.io/Watson/
> add watson status plugin

- Dev/Virtualbox/virtualbox-running_vms.30s.rb
A plugin to display and shut down (save) running Virtualbox VMs.
Got the idea from vagrant.30s.pl. I have VMs that are not in vagrant and I am most interested in seeing if there is any VMs running when they dont need to.
> Add Virtualbox Running VMs plugin

- Finance/transferwise-currency-tracker.1m.py
Sometimes Transferwise returns exchange rates to 7-8 decimal places, which pollutes the bar.
> Truncated exchange rate to 2 decimal places

- Network/ping.10s.sh
- Added a few color themes, including for color blind people
- Added header documentation so it'll look more interesting
- Added preview image
- Added FONT and MENUFONT settings to make tweaks easier
- Added Refresh button
- Changed how color is applied, so it can be applied on all rows
> Updated ping.10s.sh with color themes and refresh

- System/uptime.1m.sh
Added *flags* `PLURAL` for plural or singular output, and `VERBOSE` for including some values even when they are 0.
The variables `DS`, `HS`, `MS`, `SS` and `SEP` can be modified to change the output to own preference.
**** 
As an example, the user may prefer:
PLURAL = 0
SEP = " : "
DS = "d"
HS = "h"
MS = "m"
SS = "s"
To get output like:
> [ ↑ 2d : 10h : 5m ]
****
Or in another language, in spanish:
PLURAL = 1
SEP = ", "
DS = " día"
HS = " hora"
MS = " minuto"
SS = " segundo"
To get output like:
> [ ↑ 2 días, 10 horas, 5 minutos ]
> Rewrote the uptime plugin for easier customization

- System/uptime.1m.sh
Adding the fix of the linting recommendation of changing `echo $INFO` to `echo "$INFO"` changes the parameters in the `awk` command.
> Fixed error because of linting fix in uptime

- Network/ip-flag.2m.rb
This is for when there's no internet connection or stuff like that.
We could use 🚩 or 🏁, since they're flags that do not belong to a country. I prefered 🚩 because red is used for warnings / errors.
> Added exception handling for ip-flag

- Network/external-ip.1h.sh
A DNS lookups are faster than http requests.
> Speeding up external IP discovery by using dig and opendns

- Music/spotify.10s.sh
- Missed the ability to quickly switch to the Spotify application from the menulet. This was easily fixed by "relaunching" the application.
Cleaned up the code a little by
- Making one function, `tellspotify`, that will handle every Applescript `tell application "Spotify" to X` interaction. Used in multiple places.
- Removing multiple if statements in favor of a case switch.
> Spotify improvements

- Web/AppStore/average_app_store_review_times.rb
This is a plugin to show average review times iOS & Mac App Store.
See also [my repository](https://github.com/mfks17/bitbar-plugin-AppStore).
> add Average Review Times Plugin

- Linode.5m.php
A bitbar plug-in to show the status of your Linode(s). Requires linode-cli to be installed (https://www.linode.com/docs/platform/linode-cli).
> Added new plugin to check status of Linode(s)

- Dev/Homebrew/homebrewcask.1d.sh
using "bash=... param1=..." notation rather than putting arguments into "bash=...". For compatibility with bitbar v1.9
> compatibility fix

- System/uptime.1m.sh
The error was caused because `uptime` sometimes has a leading space (when the current time has a 1 digit hour), so when the double quotes were added around the `$INFO` to `"$INFO"`, echo doesn't trim the leading whitespace automatically anymore.
> Finally fixed error because of linting fix

- Dev/GitHub/github_status.10m.py
When GitHub problem occurs, I want to visit the official status page.
FAO: (@blockloop)
> [GitHub status] Add link to official github status

- Dev/BitbucketServer/stash-pull-requests.2m.rb
Displays a list of open pull requests in for all repositories in a specified project on Bitbucket Server (née Stash) in which the user is a participant. Results are sorted by last update (ascending), and are prefixed with a character to indicate participation type: A for author, R for reviewer, and nothing for other (e.g. added a comment). Each entry is clickable and will take you to the pull request page.
> Adds Bitbucket Server (Stash) Pull Request plugin

- Lifestyle/transmission.4m.py
Checking transmission status, info and allowing adjustment to alternative speed.
Requires a single initial setup: `python transmission.4m.py init`
This plugin displays all not yet completed torrents using "transmission-remote" cli.
You can pause any torrent in the list by selecting them.
If all active downloads have completed, but some torrents had been paused, the oldest one will be unpaused automatically.
> Transmission remote status plugins

- Network/ssh-tunnel.1s.sh
This plugin makes you easily start or stop a SSH local/dynamic port forwarding connection in the background.
> Add ssh-tunnnel plugin

- Dev/GitHub/notifications.30s.py
The release urls in the nofications api are actually the API release ID, they look like
`https://api.github.com/{repos}/{owner}/repo/releases/{release_id}`. Stripping the `api.`
and `/repo` parts just makes a URL that 404s. The actual html page follows a different
format, namely `https://github.com/{owner}/{repo}/releases/{tag}`.
Seemingly the only way to properly get the html url is to fetch the api of the particular
release and extract the `html_url`.
> fix(github/notifications): render correct release urls

- System/clipboard-history.3s.sh
On my systems wc -c file was also outputting the filename with the count and caused the script to fail the numeric compare.
> Fix wc output to show count only.

- Web/Twitch/livestreamer-now-playing.5m.js
New plugin, based on code stolen with love from the [existing Twitch plugin](https://github.com/matryer/bitbar-plugins/blob/master/Web/Twitch/play-with-livestreamer.5m.js). 
The existing plugin shows the top N games for a configured game (eg Dota). This plugin shows the currently live streamers that you follow, which game they are playing, with alt-text showing watch count and the streamers title:
Effectively being analogous to visiting https://twitch.tv/directory/following
It uses your auth key setup with livestreamer. If you haven't already set this up there is a link that runs the standard livestreamer auth setup process (twitch oauth page -> livestreamer page with instructions on where to paste your new key):
> New plugin: List of live twitch streamers that you follow

- Environment/solaredge.5m.py
Plugin for monitoring solar electric system power and energy generation as reported by SolarEdge inverters.
Requires a SolarEdge Site ID and SolarEdge API key.
Support for configuring the following:
- System wattage for calculating the current day’s efficiency
- CO2/lbs per MWh for your region for calculating CO2 offset
- Awake and sleep icons for toolbar
I put this in the Environment directory simply because I didn't see a more appropriate place. Please let me know if I should put it somewhere else.
> Add SolarEdge Monitoring plugin

- System/mdf.1m.sh
`mdf` displays a rectangular icon on the Mac OS X menu bar which is filled in proportion to disk space used on the primary disk. Clicking the icon opens a dropdown containing details of disk space utilization for each physical disk.
> New plugin: mdf - Disk usage stats

- Lifestyle/unsplash-background.3h.sh
A BitBar plugin that periodically change all desktops/spaces background to a random unsplash photo. There's also an option to manually choose 'Next Image' if you're unhappy with the one you've got :)
> Add 'Unsplash Background' plugin

- Dev/Redmine/redmine-show-my-task.1m.rb
The advantage of #!/usr/bin/env ruby is that it will use whatever ruby executable appears first in the user's $PATH.
> Small fix for redmine plugin.

- Network/vpn_advanced.sh
The existing `vpn-check.3s.sh` script simply checks VPN status. I wanted to actually connect/disconnect the VPN as well.
This script has the following features:
* Will actually launch a VPN connection and wait for it to complete
* Configurable and could work with any CLI VPN client
* Will update the menu item instantly after connecting/disconnecting
Example:
> Add more advanced VPN status/connection script

- Web/StackOverflow/reputationizer.5m.sh
If there is no internet when the script runs the `greater than` comparison fails. This change handles more gracefully this situation by printing a question mark.
> Stackoverflow - handle no internet connection

- Web/Reddit/subreddit_links.rb
This pull request addresses issue #416, where the request to get subreddit links was receiving an HTTP 429 Error. 
That error was being received because reddit was rate-limiting our request when it was coming in from the default user-agent Ruby uses in the Net/HTTP library. We now specify a generic bitbar user-agent when we send the request. That user-agent can also be changed on a per user basis, so people can add a more detailed user-agent if they want.
> updated subreddit links to specify a user agent.

- Lifestyle/taskwarrior.4m.py
Fixes #421
This should go through and parse out the extra empty lines and only look
for lines that start with a digit (task ID) or one of the markers used
to print up the UI
Will need to have @chrisidefix check it since he is the original author of the plugin.
Thanks again for the tip and for your patience in my delayed responses :)
> Filter out extra annotations from tools such as bugwarrior

- Dev/Homebrew/brew-services.10m.rb
This PR adds a Homebrew Services plugin that allows you to start, restart and stop individual or all services. It shows a total count of how many services is started in the menu bar, and also allows you to operate on all services at once.
> Add Homebrew Services plugin

- Dev/Homebrew/brew-services.10m.rb
Forgot to actually use the *All* menu when fixing the Rubocop warnings.
> [Dev/Homebrew/brew-services] Fix All menu

- Dev/Checkman/checkman.10s.rb
This plugin simulates Checkman functionality, allowing you to use all its
plugins and creating checks in external files. It downloads Checkman's plugins
on demand, so you don't need to install Checkman itself.
To learn more about Checkman, and learn about its existing plugins, see:
https://github.com/cppforlife/checkman#included-check-scripts
Configuration: Same as for Checkman, check https://github.com/cppforlife/checkman#configuring-checkman-via-checkfiles
Missing/Not yet implemented:
- Notifications/Stickies
> Adding Checkman Simulator plugin

- Network/external-ip.1h.sh
In Network/external_ip.1h.sh
Do not add a trailing newline when copying an external IP address to the clipboard.
> Remove trailing newline when copying IP address to clipboard

- Music/nowplaying.5s.sh
e.g.:
" - 2012 Remastered Version"
" - Single Version"
> Get rid of Spotify's redundant info from track title

- Dev/Homebrew/package_manager.7h.py
FAO: @kdeldycke
[mas](https://github.com/argon/mas) allows you to manipulate Mac AppStore applications from the command line.  In it's current version it does not display information on the installed version of the application.  Watch argon/mas#26 for potential fixes.  For now, `installed_version` is reported as `''` which works pretty well:
Also, did some cleanup on how `stderr` is handled and displayed.  Much cleaner now w/ less whitespace and doesn't display warnings as errors. (`process.returncode` check for truthiness.)
> MAS support

- Dev/GitHub/notifications.30s.py
Huge rewrite of the github notifications plugin, inspired by notes from @bjfletcher
Following new features:
- Notifications are grouped by their repository, each with a leading title
- Opt+Click on repository name will mark all notifications in that repo as read
- Shows icon based on: issue, issue closed, pr, merged pr, closed pr, release
- PRs have the name of the author included in the title
- Opt+Click on notification will mark as read without opening in browser
See screenshot:
/cc @flesch
> Github notifications 3.0

- .test.py
- .travis.yml
Supports multiple linters for the same file extensions.  Useful where the file extension may be shared, but the linter should be different (e.g. python2 vs python3.)
This should allow #514 to pass build tests.
> Multi linter

- Dev/package_manager.7h.py
This adds a new feature allowing "Update All" to work with any package manager.
See the implementation for Pip and Homebrew Cask for how I've done it.  Not the
only possible options, but worked well enough for me.
Additionally, a few cosmetic changes and a fix for #522 that should "just work"
for anyone.
> "Update All" for the rest of us

- Network/ip-flag.2m.rb
While I do prefer ipinfo.io, I've updated `Network/ip-flag.2m.rb` to instead use ip-api.com due to a higher rate limit.
ipinfo.io: 1000 reqs/day vs ip-api.com: 150 reqs/min
http://ipinfo.io/developers#rate-limits
http://ip-api.com/docs/api:json#usage_limits
> Change ip-flag plugin from ipinfo.io to ip-api.com due to higher rate limit

- Network/ping.10s.sh
If you have sites with sub 1 ms ping, it would be seen as down.
It still says zero if there is no contact.
This is my ping
```
$ ping google.dk
PING google.dk (212.98.120.16): 56 data bytes
64 bytes from 212.98.120.16: icmp_seq=0 ttl=59 time=0.956 ms
64 bytes from 212.98.120.16: icmp_seq=1 ttl=59 time=0.918 ms
64 bytes from 212.98.120.16: icmp_seq=2 ttl=59 time=0.934 ms
^C
--- google.dk ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.918/0.936/0.956/0.016 ms
```
> Round up number if it is a decimal

- Dev/Homebrew/brew-services.10m.rb
Homebrew taps folder has moved from `/usr/local/Library/Taps` to `/usr/local/Homebrew/Library/Taps`
> Fix Brew Services path after Homebrew update

- Dev/MetaPackageManager/meta_package_manager.7h.py
Latest stable release of the v1.10.0 BitBar plugin fixes parsing of versions with latest `mas` 1.3.1 (see: https://github.com/kdeldycke/meta-package-manager/commit/3128503af0ad57bae07be04b65e9c9e1d9d0a059 ) and also brings the currently installed versions of `mas` packages (see: https://github.com/kdeldycke/meta-package-manager/issues/4 which address a comment at https://github.com/matryer/bitbar-plugins/pull/498#issuecomment-247801247 ).
> Upgrade to Meta Package Manager v1.10.0.

- Tools/PagerDuty/pagerduty.30s.rb
Allow selection teams from which to show incidents.
> Add support for team ids in pagerduty plugin.

- Time/unixtime.5s.sh
Apparently the date was called twice:
1. output date in default format
2. parse default format and covert to +%s
This commit avoids the parsing step.
> Simplify unixtime.5s.sh

- Dev/Homebrew/brew-updates.1h.sh
Only show updates when we can actually initiate an update
> Suppress showing updates for pinned formulae

- System/postgresql-status.1m.sh
Hi,
I have created a new BitBar plugin. Please add it the repository plugin.
It shows the postgresql server status installed on localhost. And show the shortcuts for managing server instance.
It is a sister product of [mysql status plugin](https://github.com/matryer/bitbar-plugins/blob/master/System/mysql-status.1m.sh). The concept and the code are very similar to mysql's one. 
Kenji
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matryer/bitbar-plugins/598)
> New plugin: postgresql server status

- Weather/ForecastIO/weather.15m.py
The location lookup should really be HTTPS. Doesn't look like the country lookup supports HTTPS.
> plugins-weather: switch location lookup to HTTPS

- Web/Reddit/subreddit_links.rb
Was getting the following error:
"A JSON text must at least contain two octets!
Content is currently unavailable. Please try resetting."
Modifying the default port and adding ":use_ssl => true" to the Net::HTTP.start block resolved this issue for me.
> Modified to support SSL

- Dev/Docker/docker-status.1m.sh
If docker-machine env not set by default it writes "Cannot to connect to docker host" message. On the other hand at this point there is no need to check running containers.
> Remove unnecessary docker ps

- Network/bandwidth_primary.1s.sh
I'd like to propose a new plugin that shows network bandwidth usage for primary interface in Megabits/s. It is based on `bandwidth.1s.sh`.
I thought about updating `bandwidth.1s.sh` but decided to make new one as there are too many changes.
What changes:
* only gather data about 1 interface (much faster and can now gather data for bit longer interval otherwise with `0.1` sec sampling rate the data is too spikey).
* gather data in Kbit/s and convert to display Mbits/s (perhaps this could be dynamic, based on current rate)
> New plugin: Network/bandwidth_primary.1s.sh

- Dev/MetaPackageManager/meta_package_manager.7h.py
This is the first BitBar plugin of the v2.x series, which is now entirely dependent on the [`mpm` Python CLI](https://pypi.python.org/pypi/meta-package-manager).
Relying on `mpm` makes the BitBar plugin tiny and easier to maintain: all the logic is now coded in the external `meta-package-manager` Python module. This include searching for package manager, synchronizing repositories, listing outdated packages, upgrading them and formatting BitBar menus.
It also makes the BitBar plugin future proof, as support for new package manager will be implement in the `mpm` CLI.
This concludes the migration process discussed 4 months ago in #525 .
> Upgrade to Meta Package Manager v2.1.0.

- System/Battery/watt-meter.20s.py
Displays current Watt usage and highlight Green/Red depending on low/high usage. The script support different thresholds depending on model/cores, but values (especially MacBook Pro) should be tested and tweaked.
> Add watt-meter for displaying current drain

- Dev/MetaPackageManager/meta_package_manager.7h.py
This version adds a new alternative table-like rendering, with all packages placed in submenus, one per package manager. This alternative version is not active by default.
> Upgrade Meta Package Manager plugin to v2.2.0.

- Dev/Nagios/thruk.py
Without this there is this error : 
➜  bitbar ./thruk.py 
Traceback (most recent call last):
File "./thruk.py", line 56, in <module>
if not checks['hosts'] and not checks['hostgroups'] and not checks['services'] and not checks['servicegroups']:
KeyError: 'services'
> fix thruk plugin

- Music/itunes.10s.sh
After a reboot I have iTunes set to start automatically and hidden. It does so in some half-open state apparently that causes all the AppleScript commands to hang and eventually timeout.
The change below captures this quickly and handles in a more elegant manner - preferred over seeing an error in the bitbar display
Thought others might find it useful as well
> handle when iTunes running but not responsive

- Network/dnsswitcher.1d.sh
Documented at https://developers.google.com/speed/public-dns/docs/using#google_public_dns_ip_addresses
> Network/DNSSwitcher: Add Google IPv6 DNS servers

- System/Battery/trackpad-system_profiler.1m.rb
Yet another Trackpad battery plugin, for some reason the another one was not working.
Big thanks to @alexandregz, since I used his code from its Keyboard plugin to build this one. 😬
> Adding trackpad battery plugin

- Time/persiandate.1m.sh
[Persian calendar](https://en.wikipedia.org/wiki/Iranian_calendars#Modern_calendar:_Solar_Hijri_.28SH.29) is not natively supported by Mac OS. I added a simple plugin to show the Persian date using BitBar. The plugin uses [jcal](http://brewformulas.org/jcal) which can be installed using brew.
> Added Persian date plugin

- Time/worktime-tracker.1s.rb
A simple worktime tracker.
Functionality:
* Start / stop / pause / resume the timing session.
* Keep history records and export to a txt file.
* Rename session.
> Add worktime tracker

- Decred/decred-btc-poloniex.30s.sh
This plugin provides the current Decred price in BTC on the Poloniex exchange.
It takes influence from the [Monero BTC Plugin](https://raw.githubusercontent.com/matryer/bitbar-plugins/master/Monero/monero-btc-poloniex.30s.sh) as a base. Credit is included in the comments of this plugin.
> New plugin: Decred price in BTC on Poloniex

- System/launch-agents.10s.sh
Some launchctl services might have names that are substring of other services and the existing grep command thus returns a multiline result.
> Restrict grep pattern for matching service

- Network/pi-hole.1m.py
Was getting error with newest version of pi-hole:
```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
This seems to fix
> Fix pi-hole script

- Lifestyle/taskwarrior.4m.py
Places square brackets around IDs, preserving right padding. A rstrip alone is not enough, as the padding gets mangled later within BitBar, before display.
Resolves  #780
Tested to work with an empty task list and with 1 and 2 digits task IDs
> Handle Taskwarrior task list alignment issues with multi-digit IDs

- Network/pi-hole.1m.py
Supports all metrics exposed by the pi-hole API dynamically
> Pi-hole: Dynamically support all provided api metrics

- System/active_gpu.1m.py
Adds ability to display currently active GPU in your Mac. See below example for Intel vs. AMD graphics in the 2016 MacBook Pro with Touchbar.
> Add script for displaying currently active GPU (discrete vs. integrated)

- System/clipboard-history.3s.sh
changed parenthesis on the clear function so that "$tmp_dir" would expand to the actual directory.
> rm -f "$tmp_dir/item-*.pb"  -->  rm -f "$tmp_dir"/item-*.pb

- Finance/yahoo-stock.1m.py
The google-finance ticker died today (of this PR) due to google killing the url used.  Taking it's formatting, and color scheme, created a plugin to use the yahoo API as a data source.
> Add python yahoo stock getter, like the gfinance one

- Time/countdown.1s.py
I'm adding additional help text to let users know that they can use an sh file to call this script with the right arguments as discussed [here](https://github.com/matryer/bitbar-plugins/issues/849).
> Add help text to tell users to use an sh file for countdown.1s.py

- System/cpu-load.5s.sh
Displays CPU load as a simple percentage.
Advantages:
- does not use `top`
- no dependencies
> New plugin: CPU Load

- Dev/Docker/docker-status.1m.sh
Currently this plugin support only docker-machine and dlite.
Since docker for Mac, we have native support to docker in Macs, so, I changed this plugin to support it
> Add support for docker native

- System/keyboard-symbol.py
Moved the demo image into the `bitbar.image` tag
so it displays correctly on the plugin website.
> Fix image metadata in keyboard-symbol.py

- Time/pomodoro2.30s.sh
Pomodoro timer with more features than the one that's already included in the repo.
It supports long breaks, can be paused, run script, etc.
It works on Linux with https://github.com/p-e-w/argos and that's where I use it and where I tested it.
I don't have Mac OS X available so I would appreciate if someone could test it there and send me screenshots that I can include in the script's metadata.
I tried to make the script fast and light on resources. It doesn't spawn external processes when possible (like cat, cut, etc.). Apart from notifications and ``date`` on MacOS X it's pure bash. As a result the number of CPU wakeups is very low. It can be run e.g. every 30s and then the impact on resources is really negligible.
> Add a new plugin in Time: Pomodoro Timer

- Network/protonvpn.15m.py
ProtonVPN is touted to be a highly secure VPN created by the team that developed ProtonMail. They provide status(current load) of all their VPN servers using a public [API](https://api.protonmail.ch/vpn/servers) used in [this](https://protonvpn.com/vpn-servers) webpage
This BitBar/argos plugin displays the current load of user-selected servers and/or servers under free-tier updated every 15 minutes. The plugin provides users with a suggestion by displaying server with minimum load.
This plugin is useful to select one of ProtonVPN's free tier servers as they tend to be heavily used. Or, a geographically close server with minimum load from a custom list.
> Added new plugin ProtonVPN Server Monitor

- Tools/chunkwm_skhd.1s.sh
Hi, I've been playing with:
- Windows manager for macOS: https://github.com/koekeishiya/chunkwm
- Hotkey daemon: https://github.com/koekeishiya/skhd
and made this bitbar-plugin to
- Show the display id and layout mode,
- Restart chunkwm & skhd services
- Stop chunkwm & skhd services
Feel free to merge this if you think it might be helpful for others. I am also happy to provide more info in necessary. Thanks
> New Plugin: chunkwm/skhd helper

- Dev/GitHub/github-ci.1m.php
Displays an icon with a dropdown containing status of continuous integration checks across Pull Requests you've authored.
The plugin will pull in status checks for each Pull Request found for the configured repositories authored by the configured username. Each Pull Request will have a submenu for the list of checks associated with it.
Users will need to generate a Personal Access Token in Github and set up a `~/.bitbarrc` configuration with the an added section containing:
```
[github_ci]
access_token=xxx
username=jordanandree
repos[]=jordanandree/bitbar-github-ci
repos[]=jordanandree/dotfiles
```
> New Plugin: Github CI Status

- Network/dnsswitcher.1d.sh
Adding a "default" DNS. (Unsetting the DNS and letting it become router-assigned)
Especially useful when you need to navigate to a transition page to use free wifi, for example.
> Add "default" DNS to DNS Switcher

- Dev/GitHub/github-contribution.10m.rb
Displays GitHub contribution count by day, like a following capture.
This plugin will get the counts from the contribution section on GitHub user's overview page based on given username.  User can configure username and display number of contributions with ~/.bitbarrc file.
```rc
[github_contribution]
username = mizoR
max_contributions = 10
```
Thanks!
> Add Github Contribution plugin

- Network/isccond.5m.sh
This plugin gets the current status code from SANS ISC ([more info](https://isc.sans.edu/infocon.html)) and displays the current status in the appropriate color.
> Added ISC condition monitor

- Dev/PhpStormXdebugStatus/PhpStormXdebugStatus.3s.sh
The plugin is really simple, it checks if the xdebug default port (9000) is in use. If it is then we set the status to on.
> Add phpstorm xdebug status plugin

- Dev/Git/get_pull_requests_bitbar.1h.rb
Fixed: CRLF issue when used with Ruby 2.4.x
> Repos and other configs are now read from ~/.repos.yaml

- Music/spotify.10s.sh
Some bugfixes and QoL changes.
Note:
The buttons now are more DWIM [do what I mean] in spirit -- the idea is to not use the interface more than necessary. For example, pressing "Previous" will now seek to the beginning of the track and THEN go to the previous track. Previous was almost impossible to use before this change because you had to press it twice and be very quick about it. Furthermore, if the playback is currently paused, Previous and Next will additionally start playback, which is what is desired more often than not.
Full list of changes:
- Make 'prev track' seek to position 0 first.
- Correctly display the updated play state after pressing play/pause.
- Make prev/next play the prev/next track if playback is currently paused.
- Fix the track/artist/album info being unreadable …
> Improve Spotify plugin

- Lifestyle/unsplash-background.3h.sh
The unsplash random route must have changed since this script was first written. On my version of curl(7.52.1 macos), curl does not follow the 302 redirect without the -L flag. Adding it fixes the functionality.
```
rlyshw in ~/.bitbar
⚡ curl --version
curl 7.52.1 (x86_64-apple-darwin13.4.0) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```
> Add -L flag for the curl to unsplash

- .test.py
- .travis.yml
- Network/bandwidth_total.2s.lua
This plugin shows current total bandwidth over user-specified interfaces, with separate interfaces in context menu.
It is written in lua with a single call to ifstat. It is 30% smaller (peak memory use) and slightly faster than the bash + ifstat + awk versions.
> Add support for lua plugins + network bandwidth plugin in lua

- Lifestyle/syncthing.10s.sh
CPU usage was incorrectly multiplied * 100
> syncthing: fix incorrect cpu usage

- System/Battery/watt-meter.20s.py
Fix "DeprecationWarning: The readPlistFromBytes function is deprecated, use loads() instead"
> fix deprecation in watt-meter.20s.py

- .travis.yml
Travis CI is failing on some recent pull request builds:
- [Build #2009](https://travis-ci.org/matryer/bitbar-plugins/builds/444790176)
- [Build #2003](https://travis-ci.org/matryer/bitbar-plugins/builds/441034070)
The `go get -u github.com/golang/lint/golint` step in the Travis CI results in the following error:
```sh
$ go get -u github.com/golang/lint/golint
package github.com/golang/lint/golint: code in directory /Users/travis/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
The command "go get -u github.com/golang/lint/golint" failed and exited with 1 during .
Your build has been stopped.
```
The step has been changed to `go get -u golang.org/x/lint/golint` according to the installation instructions in the [Golint](https://github.com/golang/lint) README. …
> Update golint install step to fix Travis CI error

- Network/bandwidth.1s.py
Here is a python implementation of the banswidth.sh plugin
Instead of focusing on one interface ("ifstat -n -w -i en0 0.1 1") it display upload and download speeds for all interfaces in the bar, then for all instefaces in dropdown menu.
> Pull request bandwidth.1s.py Plugin

- Music/itunesRating.10s.sh
- Time/CalendarLite.1m.sh
When no song is selected, the ituneRating script shows an error message like this:
After the fix, it looks like this:
> ituneRating.sh: inhibit the error message when no song is playing

- System/copy-to-clipboard.sh
Instead of sometimes passing copy, use bash properly to run pbcopy.
> Simpler copy-to-clipboard.sh

- Web/xkcd.1h.sh
Fix __Explain XKCD wiki__ URL by adding a missing `'` at the end of the `href`
> [ADD] Missing quotation mark (Explain XKCD wiki)

- Messenger/slack-unread.1s.py
The previous implementation took my machine about 4.5 seconds to execute due to requests. By using threads to minimize the request waiting time, I managed to achieve under 0.8 second execution time.
> Use threading in slack-unread

- Music/itunes.10s.sh
The first time the script runs on a new track it will print the non-posix filename as the first line of output and display it in the menu bar instead of the music notes, state_icon and track + artist.
Example screenshot - https://www.dropbox.com/s/n7jvqw2nnr92p68/Screenshot%202019-02-16%2013.06.12.png?dl=0
> Don't print non-posix album art image filename

- Web/HackerNews/hn_front.120m.py
If internet isn't up by the time the plugin loads, the user must wait 120 minutes before the plugin will refresh. This allows the user to manually refresh the plugin, thereby refreshing the feed.
Original contributor: @amrrs
> [Web/Hacker News] Add an item to manually refresh plugin (feed) when internet connection isn't available

- Dev/GitHub/github_status.10m.py
FAO: (@blockloop)
:link: https://status.github.com/messages
```
$ curl -s https://status.github.com/api/last-message.json | jq
{
"status": "good",
"body": "Everything is operating normally.",
"created_on": "2018-12-18T18:26:50Z"
}
```
```
$ curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json | jq
{
"page": {
"id": "kctbh9vrtdwd",
"name": "GitHub",
"url": "https://www.githubstatus.com",
"time_zone": "Etc/UTC",
"updated_at": "2019-02-26T06:57:45.424Z"
},
"status": {
"indicator": "none",
"description": "All Systems Operational"
}
}
```
See https://www.githubstatus.com/api
> Use new GitHub status API

- Web/xkcd.1h.sh
This was fixed and merged in the https://github.com/matryer/bitbar-plugins/pull/1247 PR, but still not there.
- On my system I need to disable line wrapping by using the `-w 0` to make it work properly
> [FIX] xkcd base64 Image Decoding

- Web/commitstrip.1h.sh
- __jq path__: On my machine, `jq` path is not `/usr/local/bin/jq` it's `/usr/bin/jq`. 
To match all jq installs (`/usr/local/bin/jq`, `/usr/bin/jq`, `~/bin/jq` or `whatever jq path`) we can use `command -v jq` to get current `jq` path.
- __base64 Image Decoding__: On my system I need to disable line wrapping by using the `-w 0` to make it work properly
> [UPDATE] jq path + [FIX] base64 Image Decoding

- Finance/stock-ticker.30s.py
There are certain conditions when the request returns data in the following format:
``` {u'quote': {u'symbol': u'[ticker]', u'changePercent': None, u'change': None, u'latestPrice': [price]}}}```
This adds a if statement to prevent getting an error symbol by printing the `latestPrice` value when the API interface returns `None` which is intepreted as a `null` value.
> Add Conditional For `None` Value in JSON

- Time/progress-procrastination.15s.sh
Forked from [aurorabbit](https://github.com/aurorabbit) and [Mucahit](http://github.com/mucahit) (who submitted a [simpler version](https://getbitbar.com/plugins/Time/progress.1h.sh) w/ latest on 2156883).
> Progress Bar for Work Day (to beat procrastination!)

- Tools/desktop_cleaner.rb
`DesktopCleaner#desktop_path` returns `Pathname`. but `Pathname` does not respond to `#gsub`.
Use `#to_s` to be string before encoding.
> Fix url encoding bug

- Network/wifisignal.sh
New plugin that utilizes the `airport` CLI tool to grab the active wifi signal & noise data, then perform basic calculations to show signal strength & quality.
Signed-off-by: Bryan Stone <aegixx@gmail.com>
> Wifi Signal Strength & Quality

- System/Battery/battery-status.20s.py
Fixed an error that'll happen on a machine that uses 2 or more version of python.
BitBar plugin will utilize the default system python version.
> fixed posix error no 2

- System/Battery/battery-status.20s.py
Fixes problems referenced in #1130 and #1309 by using the right split of the output and ensuring we use python3
> fix battery plugin and ensure we use python 3

- AWS/cloudwatch-alarms.30s.py
Adding image metadata to the plugin so that the website https://getbitbar.com/plugins/AWS displays the image alongside the plugin
> add image metadata for the cloudwatch alarm plugin

- Dev/GitHub/github-contribution.10m.rb
Fixed following warn:
```rb
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
> Fix Ruby 2.7.0 deprecation warning

- System/DoNotDisturb.1s.py
When selecting 1 minute it actually activates Do Not Disturb for 5 minutes.
This commit fixes this little bug.
> Hotfix for Do Not Disturb

- Music/nowplaying.5s.sh
macOS Catalina rebranded `/Applicaitons/iTunes.app` to `/System/Applications/Music.app`.
This will add support for Apple's native Music app... tested working in 10.15.1... and immediately takes effect (upon next refresh), no app restart necessary.
> fix: nowplaying support for Catalina Music.app

- Web/HackerNews/hacker_news.1m.rb
I'd like to let HackerNews plugin support dark mode.
> Remove color=black so that HackerNews supports dark mode

- Weather/DarkSky/weather.15m.py
As per OpenCage best practices https://opencagedata.com/api#bestpractices
add no_annotations=1 since this script doesn't use any of the information in the annotations.
That said, might be interesting to use OpenCage's "sun" annotation which is the time of sunset and sunrise at that location:
https://opencagedata.com/api#sun
> add no_annotations=1 to OpenCage API call

- Music/music-controls-info.10s.sh
- Music/music-controls-like.10s.sh
- Music/music-controls-next.10s.sh
- Music/music-controls-playpause.10s.sh
- Music/music-controls-previous.10s.sh
Duplicated the iTunes references for all `music-controls-*.sh` plugins.
Tested and confirmed all are working in macOS Catalina (10.15.3)
> fix: add music-controls support for Catalina Music.app

- Time/aideadlines.15m.py
This plugin counts down the days left until the deadlines of AI conferences, where the list is maintained at <https://github.com/abhshkdz/ai-deadlines/>.
The dependencies are python3, along with third parties (pyyaml, pytz, tzlocal, wget). While they can be manually installed via `pip`, the plugin itself provides a button to automate the process.
It may create several files (starting with a dot to hide from Bitbar) to store internal data.
> aideadlines, first PR

- Cryptocurrency/Dash/dash-coincap-binance.5m.sh
- Cryptocurrency/Dash/dash-coincap-poloniex.5m.sh
Coinmarketcap stopped providing (unlimited) free API access unfortunately, have to use another data source. Coincap.io looks like a good choice for now. Also adding Binance.com as a more trading volume/less bandwidth consumption alternative to Poloniex.com (API of the latter is also failing sometimes for some reason).
> Cryptocurrency: Dash: Replace Coinmarketcap.com api with the one from Coincap.io, add Binance as an alternative to Poloniex

- Dev/Docker/docker-status.1m.sh
Since Docker for Mac is [no longer packaged with `docker-machine`](https://github.com/docker/for-mac/issues/4208#issuecomment-576811681), docker-machine should not be a dependency; currently an up-to-date install produces an error for `docker-machine: command not found`. 
This removes the docker-machine requirement by preventing the variables from being set if the commands don't exist. This way the [empty string conditional](https://github.com/matryer/bitbar-plugins/blob/7bddc2f1692a80c774535f6aad18d2c2f45c2403/Dev/Docker/docker-status.1m.sh#L49) works as intended, and the `[ -n ... ]` tests don't return true when they shouldn't.
> Remove docker-machine dependency

- Lifestyle/sureflap.15s.rb
We get UTC times back from the API.
It appeared off by an hour after daylight saving time was introduced.
> SureFlap script: convert UTC to localtime

- Dev/Gitlab/gitlab_merge_requests.js
This catches a case where the API returns null instead of an empty object.
> Fixes an undefined error

- Finance/yahoo_stock_ticker.10m.py
Adding a plugin written in Python3, that shows major stock indices in the menu bar and stock symbols in the dropdown menu. You can also set price alarms for BUY/SELL limits, which will notify you when the limit is reached.
Flake8 did not show me any linters, but I also excluded the 'line too long' rule.
> Add yahoo stock ticker plugin

- System/DarkModeToggle.sh
Maybe some typo or something is left in previous script.
I'm not familiar with `osascript`. Just make it worked on Big Sur.
> Update System/DarkModeToggle.sh for supporting Big Sur

- Network/dnscrypt-proxy-switcher.10s.sh
The way this script was checking the macOS version was flawed—it assumed that the major version was 10, and it also called the second part of the version number the "major" version, which was incorrect.
Based on my research, the correct way to reset the DNS cache on 10.15 and 11.0 is the same, and it includes `dscacheutil -flushcache`. But the script didn't previously include that command for 10.15, it fell back to the default on 10.13 and higher, only killing `mDNSResponder`. That's still the command used for 10.13 and 10.14.
I also changed the version number checks to return unique values so it's easier to troubleshoot.
> Update dnscrypt-proxy-switcher to support macOS 11

- Tools/screen.2m.sh
The conditional that checks for a 'no screens' state was erroneously only checking for a lack of return from 'screen -list'.  A successful 'screen -list' contains an 'is empty' message which prevented the
display.
This commit also adds an action to create a screen session if none currently exist.  So here we change the 'no screen' message to 'new screen session'.
> Fix 'no screens' state in screen.2m.sh plugin

- Network/internal-ip.1h.sh
This work iterates over all `en` prefixed interfaces / adapters to find the internal IP address of the machine. It then displays the details of the interface / adapter tied to the IP address.
>  Issue #938 - Fix display of internal IP address

- Web/RSSReader/rss.15m.php
This work checks if the feed data returned is an empty string. If it is, the title will be set to `No new items at this time.` and will not attempt to process the feed.
> Issue #719 - Simple RSS reader throws error if feed returns empty string.

- System/cpu-thermal-throttle.30s.sh
Plugin that displays the current CPU thermal throttling as percentage of full CPU speed (using `pmset -g therm`).
> Add CPU thermal throttling plugin

- Network/ssh-tunnel.1s.sh
The ssh-tunnel plugin prints a host every time it finds a line with DynamicForward or LocalForward. This change condenses consecutive duplicate hosts to ensure only one host is displayed in the menu, even if that host configuration has multiple forwards configured.
For example, the following SSH_CONFIG would produce two "example.com" menu items:
```
Host example.com
LocalForward 6443 127.0.0.1:6443
DynamicForward 127.0.0.1:3128
```
With this change, it only produces one "example.com" menu item.
> Deduplicate hosts in ssh-tunnel

- Music/nowplaying.5s.sh
Assume we are on Catalina or higher to start and not show an iTunes menu item. It appears "iTunes" is an alias under the hood for the new "Podcasts" app. Detect if we are on a pre-Catalina version of OS X and adjust the menu to have iTunes app instead of Music app.
Tried having "Podcasts" in the menu, but the app overall does not behave in the same way as the others. The check for the player state throws an error. Rather than dive down that rabbit hole, fix this bug and address Podcasts some other day.
> Issue #1468 - Now Playing opens Podcasts in Catalina

- Music/spotctl.10s.sh
Sometimes spotctl gets a weird response from Spotify even though everything is fine, this can just be ignored.
> Spotify Now Playing (via spotctl): ignore errors

- Time/date-picker.1m.sh
Copy to clipboard wasn't working. After removing the spaces before each bash= and putting single quotes around each $0 it is now working for me.
> Fix clipboard functionality of Date Picker plug-in

- Lifestyle/ZoomsToday/open-zoom.sh
- Lifestyle/ZoomsToday/zooms-today.1h.sh
This plug-in scans the current day in your calendar to find events containing a Zoom link. If any are found, they are presented in a list where clicking an item will open the link to that Zoom meeting.
> Zooms Today: Quickly launch the Zoom link attached to meetings in your calendar

- Tools/Slack/slack-team-notifications.1m.js
- Fix labels for group DMs
- Token in query string deprecated by [Slack](https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps). Pass token as `Authorization` header.
> Update slack-team-notifications to v1.1.1

- Dev/Hosting/Linode/Linode.5m.php
I was getting an error on the foreach loop. Ended up being the binary being used. 
Updated line 12 to use linode-cli linodes list --json which lines up with Linode's v4 api. If you have linode-cli installed it should run as expected.
> Updated to use current (v4) Linode api

- Dev/meta_package_manager.7h.py
This is a brand new version that was updated to aligns with new xbar conventions.
Changelog:
* Forces syncing of local package manager database on refresh.
* Allow switching of rendering mode from flat to sub-menu by the way of environment variable and plugin options.
* Add minimal requirement on meta-package-manager module in the invoked `pip` command.
* Each update line can be called with the option modifier to run the CLI into a terminal. Useful for debugging.
* Code linted by Black formatter.
* Drops support for Python 32.x.
Superseeds and closes #1479.
> Upgrade to Meta Package Manager plugin v4.1.0.

- Time/progress-procrastination.15s.sh
The PR adds quoting to a font name in Time/progress-procrastination.15s.sh that has spaces causing xbar to be unable to parse the output. Attached is the original error caused by this plugin:
> Fixes unquoted font name string causing 'malformed parameters: missing equals' error

- Network/pi-hole.10m.py
Add base_url as a xbar variable (VAR_BASE_URL)
Put a refresh when enabling/disable pi-hole, so that the status update directly
Update refresh time to 10m, as it seems useless to refresh every minute considering the refresh "fix"
Update <xbar.image> with a working url
> Update for the pi-hole plugin

- System/Yubikey.30m.sh
Better handle ykman return code
Now automatically create and update the .b64 image when a .png, .jpg, etc.. exist in YubiKey directory for the issuer
Directory changed from Yubikey to YubiKey (uppercase K)
You can set http link to open for each issue with the `defaults write com.xbarapp.plugins.yubikey "issuer" "https://..."` command in terminal
> v1.2 of the  Yubikey plugin

- System/recent-apps.10s.py
Here's a new plugin I wrote today. Description from [the repo](https://github.com/incanus/xbar-recent-apps): 
> A plugin to show the ten most recently used apps that aren't permanently in the Dock. The Dock only shows the latest three non-running apps, but I wanted more! Selecting an entry will launch the app. The default hotkey is `Cmd-Option-A`.
> add recent apps plugin

- System/diskAvailable.sh
The plugin runs "diskutil info" command and for me the output of the command says "Container Free Space" and not "Volume Free Space" (as the plugin expects).
I am running BigSur 11.2.3 and the plugin was raising an error window saying "Application is not open anymore".
This small tweak fixes the problem and it looks to me that with this tweak the plugin should work on both diskutil outputs ("Container" and "Volume").
Sadly, I have no way to test this on an actual machine that outputs "Volume" and some feedback would be much appreciated.
> Fix diskAvailable plugin raising error window on BigSur

- System/cpu-high-usage.5s.py
Hi!
This plugin in basically replaces `cpu-usage-kill` plugin (which actually doesn't work for now). 
It allows to detect and show the process, that consumes too much CPU (50% by default). It also shows the top processes in the submenu. If `KILL` setting is enabled, clicking to a process name kills the process.
If there no high CPU consuming processes, the plugin stays quiet (in contrast with `cpu-usage-kill`).
> Create cpu-high-usage plugin

- Network/pi-hole.10m.py
Add disable 30s and disable 5m options.
Clean up status message when your pi-hole is not reachable
Use curl instead of href tags so we don't have to open a web page in a browser
> Update pi-hole plugin

- Environment/solaredge.5m.py
Fixes syntax error (':' should be '=') in menu output text settings
> Fix #1654 syntax error in solaredge plugin

- Weather/DarkSky/weather.15m.py
The original cardinals calculation left out degrees of accuracy but also did not seem to function correctly, for example, below test of the primary cardinal points do not return the expected results of N, E, S, W, N
```
def calculate_bearing(degree):
cardinals = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
return cardinals[int(round(((6 * degree)) / 360))]
for i in (0,90,180,270,360):
print(calculate_bearing(i))
```
returns 
```
N
NE
SE
S
W
```
The suggested change fixes this and includes finer granularity,[source](https://gist.github.com/RobertSudwarts/acf8df23a16afdb5837f)
> update cardinals for Weather/DarkSky/weather.15m.py 

- System/wkma.5s.sh
This will add a plugin to show which apps prevent the Mac from going to sleep.
It also allows to kill the corresponding process and gives a brief description from the man pages.
Preview:
> Add plugin to show what apps prevent sleep

- CONTRIBUTING.md
- README.md
This PR migrates the contribution guide from the original xbar app  repo to  here, where  it makes more sense  as discussed in https://github.com/matryer/xbar/issues/754
@matryer please also delete and link this new guide in the xbar repo README, e.g.:
```markdown
From an xbar menu, choose **Preferences > Plugins...** to use the xbar app to discover and manage plugins.
You can [browse all the plugins](https://xbarapp.com/) online, or [write your own](https://github.com/matryer/xbar-plugins).
The plugin directory is folder on your Mac where the plugins live, located at `~/Library/Application Support/xbar/plugins`.
* If you're transitioning from Bitbar, move your plugins into this new folder to install them
If you'd like to contribute a plugin, head over to …
```
> Migrate contribution guide to this repo

- Dev/Kubernetes/minikube.5s.sh
- Network/openfortivpn.sh
- Network/vpn_advanced.sh
- System/Battery/watt-meter.20s.py
- System/HandoffToggle.1d.sh
- System/diskAvailable.sh
- System/power_wattage.30s.sh
- System/samplerate.sh
See #1688
A [remaining reference](https://github.com/matryer/xbar-plugins/blob/b74b4799e6020df9e2d88c6ef536e852e167840c/Network/updatevpnbookpass.1d.sh#L73) is in `Network/updatevpnbookpass.1d.sh` as it also references a path `/Applications/Utilities/Keychain Access.app` which no longer existing on newer systems, so I guess that line is broken (hence commented).
> Remove unnecessary `/usr/sbin` and `/sbin` references

- Network/iCloud-Private-Relay-Status.6m.sh
This plugin checks if the IP used for an insecure http request can be found on Apple's list of egress IPs used by [iCloud Private Relay](https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay) and shows a happy green sparkle if so, or a scary red flag if not. This plugin is based on [My External IP](https://github.com/matryer/xbar-plugins/blob/main/Network/external-ip-1.0.1h.sh) by CodinCafe.
> Add iCloud Private Relay status indicator

- Dev/GitHub/github-review-requests.5m.py
This PR sets default filter that excludes drafts from the list and switches python to version 3.
> github-review-requests.5m: Exclude draft PRs by default

- Dev/GitHub/notifications.30s.py
Hi,
I was getting this error:
```
Traceback (most recent call last):
File "~/Library/Application Support/xbar/plugins/001-notifications.30s.py", line 256, in <module>
print_notifications(github_notifications)
File "~/Library/Application Support/xbar/plugins/001-notifications.30s.py", line 99, in print_notifications
formatted_notification = format_notification(notification)
File "~/Library/Application Support/xbar/plugins/001-notifications.30s.py", line 133, in format_notification
formatted["title"] = formatted["title"][:79] + "…"
TypeError: can't concat str to bytes
```
And this is the way I fix it, not sure if it is the best way but it works 🙂
> Dev/GitHub/notifications.30s.py | Use textwrap to short title

- Dev/Gitlab/gitlab_merge_requests.js
Version 2 of the bitbar module has a breaking change: https://github.com/sindresorhus/xbar/releases/tag/v2.0.0
> fix(GitLab Merge Requests Plugin): pin the globally installed bitbar module to major version 1

- Network/dnsswitcher.1d.sh
Rearranging order acts as intended:
- Terminal will NOT show when a new DNS profile selected
- Bar WILL refresh when a new DNS profile is selected
> Make terminal not show and refresh bar

- Time/watson.1m.sh
The problem might have been caused by a change made to the output
of watson status command. In any case, this fix makes it compatible
with recent Watson versions.
> Find all the tags instead of '[firsttag', as currently.

- System/real-cpu-usage-chart.10s.sh
Homebrew installations on M1 Macs go into `/opt/homebrew` by default now as to avoid mixing with intel-based software under `/usr/local`.  This allows the real-cpu-usage-chart to quickly confirm if the spark dependency should be pulled from a different homebrew path.
> real-cpu-usage-chart spark fix for M1 mac homebrew

- System/ntfs.1d.sh
What's new in this update:
- Fix the problem that the second disk cannot be mounted when there are disks with the same name mounted at the same time
- Better looking icon
- Now users can fill the password in a pop-up dialog
- More detailed error reporting description in dialog
some screenshots:
<div align="center">
</div >
<div>
</div>
> Upgrade NTFS Mounter to v1.1

- Cryptocurrency/Ethereum/eth_gas_widget.10m.rb
- Cryptocurrency/Polygon/polygon_gas_widget.10m.rb
This plugin displays the gas prices for Ethereum and Polygon. For Ethereum, it is equivalent to the existing plugin below, but this plugin seems to have stopped working due to a change in the site. Please check it out.
https://github.com/matryer/xbar-plugins/blob/main/Cryptocurrency/Ethereum/gasnow.10s.sh
> Add Ethereum and Polygon gas fee plugin

- Network/simple-latency.11s.sh
Open to any feedback. 
This aims to be useful when: 
1) you're trying to document problems with the VPN in a big company. 
2) When you notice problems with a streaming application and wonder if you should start troubleshooting network issues or look at your provider's service page.
> Add a simple latency check 

- System/fan_speed.5s.js
There is already a plugin that shows fan speed, but it doesn't work on recent models.
This pull request adds a plugin for recent models.
> add fan_speed plugin for newer model

- System/showhide-files.1d.py
Since the new MacOS version, python2 isn't shipped anymore, the plugin had to made compatible with python3. The screenshot was replaced to match new options.
> showhide-files plugin: add python3 compatibility

- Music/sonosBar.py
Change the python call to python 3 and use shlex.quote on PATH_TO_SCRIPT otherwise the call and script breaks due to the space in 'Application Support'
> fix shebang & spaces in script path

- Dev/meta_package_manager.7h.py
More documentation available at: https://kdeldycke.github.io/meta-package-manager/bar-plugin.html
Changelog:
* Add a new `TABLE_RENDERING` variable to separate its effects from the initial `SUBMENU_LAYOUT` variable
* Improve alignement of version values in `TABLE_RENDERING` mode
* Fix location of binaries on Apple Silicon machines
* Tweak icons
* Improve environment variable parsing
* Check for minimal Python version
* Adds type hints
* Try to fix CLI parameter over-escaping (see https://github.com/matryer/xbar/issues/831)
* Add better compatibility with SwiftBar
* Delegate rendering to `mpm` binary itself to reduce plugin complexity
* Add `--check-mpm` option for debugging
* Bump requirement to `mpm >= 5.0.0`
> Upgrade to Meta Package Manager plugin v5.5.1

- Dev/Nagios/nagios.30s.sh
This plugin outputs Nagios status.
It's based on the `nagios.30s.sh` plugin by Rob DeSanno (@rdesanno), but improves on it in the following ways:
- Uses xbar variables for credentials and settings (no script editing required)
- Is compatible with Nagios servers that live behind a VPN.
- Output has been significantly (IMO) improved.
> Add feature-filled Nagios plugin

- Lifestyle/zoom_mute.3s.sh
This plugin adds an indicator for your mute status in Zoom. It uses an AppleScript to check the Zoom menu bar items to identify the mute status.
> add zoom_mute plugin

- Dev/Homebrew/brew-services.10m.rb
This is a complete rewrite of the brew-services plugin, based on my
brew-updates plugin.
Main functional differences from the original plugin is:
- The option to group started/stopped services together.
- Hide services you don't want shown on the main list.
- Visual style being a bit different.
- An option to uninstall stopped services.
- Overall it doesn't suffer from any of the bugs that I'd run into with
the old one.
---
I'm not sure what the policy is with a wholesale plugin rewrite/replacement like this, so I'm happy to make any changes as needed :)
New brew-services:
Old brew-services:
> feat: rewrite brew-services plugin

- Email/imap.1m.rb
Very simple plugin to check unread email from any IMAP server
No new email:
Unread email:
In case there is any email and the webmail is configured it'll show a direct link:
> New plugging to check unread emails from any IMAP mailbox

- Dev/GitHub/notifications.30s.py
Add missing image for `CheckSuite` and add href to repository actions.
Unfortunately GitHub api doesn't give us a better url 😔
> Add CheckSuite image and href

- Dev/Gitlab/gitlab_merge_requests.1m.js
- Network/dnscrypt-proxy-switcher.10s.sh
- Network/ssh-tunnel.1s.sh
- System/Battery/keyboard.1m.sh
- System/Battery/mouse.1m.sh
- System/cpu-usage-kill.5s.sh
- System/lock-screen.10h.sh
- Web/YouTube/YouTubeTicker.1m.js
- `cpu-usage-kill.5s.sh`: Remove deprecated `root=true` parameter. Closes #1846, Closes #1742
- `ssh-tunnel.1s.sh`: Remove escaped double quotes in command. Closes #1893
- `lock-screen.10h.sh`: Alter script to detect OS version and adjust command for Big Sur and later. Closes #1751
- `dnscrypt-proxy-switcher.10s.sh`: Update from upstream repository. Closes #1520
- `YouTubeTicker.1m.js`: Fix color parameter issue.
- `gitlab_merge_requests.js`: Rename file to include timing. Fix hardcoded user ID issue. Closes #1695
> March issue fix bundle

- Cryptocurrency/binance-ticker.6s.py
- Environment/conda-envs.15m.py
- Finance/transferwise-currency-tracker.1m.py
- Finance/yahoo_stock_ticker.10m.py
- Lifestyle/taskwarrior.4m.py
- Time/countdown.1s.py
- `taskwarrior.4m.py`: Use python3 and add PATH spec including M1 Homebrew location. Closes #1912, #1044
- `binance-ticker.6s.py`: Update API URL. Closes #1529
- `yahoo_stock_ticker.10m.py`: Remove invalid stock symbol
- `transferwise-currency-tracker.1m.py`: Move configuration into xbar variables. Add label variables. Closes #1242
- `conda-envs.15m.py`: Update to python3 and fix encoding error. Closes #830
- `countdown.1s.py`: Complete overhaul to use xbar variables instead of script wrapper. Closes #951
> Python fixes for March 2023

- Dev/Homebrew/brew-updates.1h.rb
- Add more granular greedy options (latest and auto-updates).
- Add post-run options for optionally running "brew cleanup" and/or
"brew doctor" after operations that modify packages.
- Add new "Upgrade All: Exclude" option which simply excludes a
formula/cask when using any of the Upgrade All operations.
- Re-style menus a bit with emoji as icons for most operations.
---
This pulls in the latest changes to the brew-updates plugin from my [dotfiles](https://github.com/jimeh/dotfiles/tree/main/xbar).
**Before:**
**After:**
> feat(Dev/Homebrew/brew-updates): new options and style changes

- Dev/Homebrew/brew-updates.1h.rb
Resolved incorrect method name when rendering list of formulas/casks excluded from "Upgrade All" actions.
> fix(Dev/Homebrew/brew-updates): fix error with exclude from all option

- System/bluetooth_inspector.10m.rb
- Changes to system profiler since plugin creation returns the Bluetooth data in a different format. This updates how the data is pulled.
> Issue #1753 - Fix bluetooth inspector error

- Time/epoch.60s.sh
A simple script to show the current UNIX or Epoch time, comma separated.
Depends upon GNU sed.
> feat: script to show epoch time, comma separated

- System/pmset.5m.sh
fix invalid display state on macos m1/m2 arm64 (ventura) caused by `SleepDisabled` not being included in `pmset -g` output if nosleep on battery was never used before
> fix m2 arm64 pmset output

- Web/zendesk.2m.rb
This plugin shows a nice count of un-solved Zendesk tickets, and a link to go view them.
I stole a lot of the code from the FreshDesk version, since that does a very similar thing, but for FreshDesk.
Here's how it looks:
To use this plugin, you need to enter your zendesk API key, subdomain, and email address in the params at the top of the script.
I hope this is useful to someome else :)
> New plugin for Zendesk tickets

- Network/bluetooth_connection.5s.sh
Requires blueutil installed.
This adds back a bluetooth connection indicator that was removed in macOS Big Sur (big shame).
> added bluetooth connection indicator

- Dev/Homebrew/brew-updates.1h.rb
The `brew outdated` command recently changed the `"installed_versions"` field on casks from a string to an array, bringing it in line with formula details.
This allows it to deal with either string or array values, and show them correctly.
> fix(xbar/brew-updates): show installed cask version(s) correctly

- Lifestyle/zoom_onair.15s.py
Recent versions of Zoom started keeping a port open after exiting meetings. Change on-air status monitoring to look for connected ports on the local hostname.
Also, newer versions of python-magicue changed to use 'LocalLight' instead of 'Light'.
> Change how zoom meetings are monitored

- System/secure-totp.sh
Other plugins keep generating tokens and put them into calls of the plugin menu. This only shows the names in the menu and generates the token only when clicking on an entry. After 30 seconds the clipboard is cleared again.
Also the secrets do not have to be inserted into the script but can be placed anywhere on disk and referenced as a file.
And since the tokens are only generated when an entry is clicked, this plugin only has to be refreshed, when there is a new entry in the secrets file.
> Secure TOTP

- Time/productivitycountdowns.1h.sh
This commit fixes the issue where the script would fail when the month number had a leading zero. Numbers with leading zeros are treated as octal in Bash, causing arithmetic errors when the month is 08 or 09.
By using arithmetic expansion, the leading zeros are removed, ensuring that the month_number variable is treated as a base-10 integer.
> fix(productivitycountdowns): remove leading zeros in month_number

- Time/WorldTimeGrid.10s.py
Here's a new plugin to show a grid of times for different time zones. Let me know if you have any notes or suggestions!
It shows the UTC time on the menu bar like this:
When you click it it shows a grid of the previous and next 12 hours, highlighting the current hour:
There's a bunch of configuration options, including which time zones to display, how many hours to go forward and backwards, and the font. It requires Python 3.
> Add WorldTimeGrid plugin

- Cryptocurrency/cryptocompare-portfolio.1m.rb
Shows your portfolio holdings at cryptocompare. (https://www.cryptocompare.com/portfolio)
Create ~/portfolio.yml with cookies before start using.
~/portfolio.yml should contain text like:
```
---
cookie: __cfduid=...; _ga=...; G_ENABLED_IDPS=google; lightsOff=1; _gid=..; sid=
```
To obtain cookie value:
- Open browser network console, open page https://www.cryptocompare.com/portfolio
- Copy cookie value from headers:
> Cryptocompare portfolio holdings

- Dev/Kaiten/kaiten-dashboard.5m.sh
This plugin lets you review all cards that are in your Kaiten Dashboard, dividing them by the ones where you are responsible and the ones where you are only member
> Added Kaiten Dashboard plugin

- CONTRIBUTING.md
Having a plugin that supports being called with multiple parameters would be useful, e.g.,
```bash
if [ "$#" -ne 1 ]; then
...default operation...
endif
if [ "$1" = "reboot" ]; then
...reboot operation...
endif
```
While the documentation suggests using `bash=$0` for the script to call itself until tonight I was not able to make it work correctly due to issues with the running path.
I decided to improve the "shell" documentation including an example on how to make the script call itself correctly using `$(realpath $0)`.
> Improved "shell" documentation with quotes and how to call itself

- Time/toggl.10m.sh
Show how many hours you've logged in [Toggl](https://toggl.com/) for the current week for one or more workspaces.
This is a simpler version of the existing [toggl.1m.js](https://github.com/matryer/xbar-plugins/blob/main/Web/toggl.1m.js) with the ability to specify which workspaces you wish to track.
> Toggl time-tracking software, hours for the week

- System/cpu-load.5s.sh
> cpu-load.5s.sh: remove Bash dependency

- Dev/GitHub/github-review-requests-TS-5m.ts
This plugin works great but has the GItHub API hard-coded. On GitHub Enterprise this API URL is different and needs to be configured. The GitHub PR Notii plugin already has this option, so I'm just adding a similar one to this plugin.
> Add API_ENDPOINT option to "GitHub Review Requests TS" plugin

- Time/rescuetime-activities.3m.py
I just developed a new plugin, and I would be excited to share it here.
**RescueTime Activities**: Monitor your RescueTime activities and distractions directly from the macOS menu bar with this xbar plugin.
Source is at https://github.com/stared/xbar-rescuetime-activities.
This plugin is inspired by the [RescueTime plugin](https://xbarapp.com/docs/plugins/Dev/rescuetime.1h.py.html) by [Paul Traylor](https://github.com/kfdm).
I rewrote it to display a detailed list of activities rather than just a summary of productive and non-distractive time.
> new plugin: RescueTime Activities

- Web/bitbar-uptime_robot.py
- Update python path to detect various ways of installation.
- Move API key to xbar variable.
- Have response time default to a `?` and only make the calculation if the key exists in the API response.
Closes #2068
> Issue #2068: bitbar-uptime_robot.5m.py: KeyError: 'average_response_time

- Dev/NugetDownloadCount.5h.py
This plugin allows you to specify a list of NuGet packages and view the download counts for all listed versions.
> Create NugetDownloadCount.5h.py - new

- Lifestyle/nightscout.1m.sh
This PR addresses an issue where the Nightscout xbar plugin displays incorrect time differences (e.g. "28988905m ago").
**Changes Made:**
- Added proper decimal handling for the timestamp conversion using `awk`
- Added `-r` flag to `jq` commands to ensure raw string output
- Ensures accurate time difference display (e.g. "2m ago" instead of large incorrect values)
**Testing:**
1. Install the updated plugin
2. Verify that the time difference shown is reasonable (e.g. "2m ago", "5m ago")
3. Monitor over time to ensure values remain accurate
Fixes #2089 
---
Note: This change maintains all existing functionality while fixing the timestamp display issue. No changes to the plugin's configuration or dependencies are required.
> Fix timestamp calculation in Nightscout xbar plugin

- Environment/electricitymaps.5m.py
Fixing a bug in electricity maps where the auth-token was passed as param instead of header.
I also took the opportunity to rename the `countryCode` variable.
> Fix bug in electricity maps

- Tools/aerospace-viewer.5s.sh
Hey!
This plugin adds active workspace visualization for the [AeroSpace window manager for macOS](https://github.com/nikitabobko/AeroSpace):
> Add AeroSpace Viewer plugin

- Cryptocurrency/multichain_gas_widget.5s.rb
- Updated @geeknees's Ethereum gas widget to use the [new V2 endpoints](https://info.etherscan.com/etherscan-api-v2-multichain/).
- Added multichain compatibility by allowing users to input a chain ID of their choice (provided that the chain is supported by etherscan)
> multichain compatibile with etherscan V2 endpoint
